### ISSUE TITLE
Should enforce that tags start with ascii characters only

### ISSUE THREAD

**Issue by jackila** [jhy/jsoup#1006]
When I use Jsoup.parse('') to parse the html 

`<p>5.到推机制，推荐会员匹配成功超过24小时不打款帐号会被冻结，扣领导人`
`<会员挂单金额5%>动态做为惩罚</p>`
`<p><br></p>`

The result come out like this:

`<p>5.到推机制，推荐会员匹配成功超过24小时不打款帐号会被冻结，扣领导人`
  `<会员挂单金额5%>`
    `动态做为惩罚`
   `</会员挂单金额5%></p>`
  `<p><br /></p>`

apparently <会员挂单金额5%> is not a tag ,is there any method  can  solve it?

**Comment by krystiangorecki** [comment]
If that's the only problematic tag you can escape it manually:
``` 
html = html.replaceAll("<会员挂单金额5%>", "&lt;会员挂单金额5%&gt;");

**Comment by SliverySky** [comment]
In this version, Chinese character is also considered as legal tag. e.g<一></一> this is not allow in chrome. String "<一>"will be mistaken as unclosed tag and be replace by <一></一>. The reason is that Character.isLetter() will consider all character in all language as letter.[https://github.com/jhy/jsoup/pull/1390](url)

**Comment by jhy** [comment]
Per the HTML spec, and in checking in Chrome: tags must start with an ascii character, and any character after that is allowed.

See [tag open state](https://html.spec.whatwg.org/multipage/parsing.html#tag-open-state) followed by [tag name](https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state) state.

So, valid tags should be:

```html
<a一>
<a会员挂单金额5>
<table(╯°□°)╯>
```

Invalid:
```
<一>
<会员挂单金额5>
<table(╯°□°)╯>
```

**Comment by SliverySky** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for your replay which let me know the reason for this problem (why <一> can't work in Chrome). And I will standardize the format of PRs. Thank you for reminder!
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                11710101
                            
                    
                        
                            
                                    11710101@mail.sustc.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 1/11/2021 21:02，Jonathan Hedley<notifications@github.com> wrote： 




Per the HTML spec, and in checking in Chrome: tags must start with an ascii character, and any character after that is allowed.

See tag open state followed by tag name state.

So, valid tags should be:

<a一>

<a会员挂单金额5>

<table(╯°□°)╯>

Invalid:

<一>

<会员挂单金额5>

<table(╯°□°)╯>





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jhy** [comment]
Thanks, fixed now
