### ISSUE TITLE
Inconsistency: Attributes.html() output differs from Attribute.html() output

### ISSUE THREAD

**Issue by cketti** [jhy/jsoup#1026]
The output of `Attributes.html()` (used when serializing a `Document`) and `Attribute.html()` differs when certain conditions are met. This is because the formatting logic exists twice with subtle differences.

**Issue 1**:
```java
Attributes attributes = new Attributes();
attributes.put("key", null);
Attribute attribute = attributes.iterator().next();

assertEquals("key=\"\"", attribute.html());
assertEquals(" key=\"\"", attributes.html());  // fails; output is ' key' (like it was a boolean attribute)
```

The code in `Attribute` suggests that everything but the known boolean attributes should be displayed like `key=""` if the value is `null`, empty, or equal to the key. Due to a misplaced closing parenthesis in `Attributes.html(Appendable, OutputSettings)` a quoted empty attribute value is never appended.

**Issue 2:**
```java
Attributes attributes = new Attributes();
attributes.put("checked", "");
Attribute attribute = attributes.iterator().next();

assertEquals("checked", attribute.html());
assertEquals(" checked", attributes.html());  // fails; output is ' checked=""'
```

`Attribute.html()` treats a zero-length `String` like `null` and only outputs the attribute key. `Attributes.html()` is missing that check.

**Issue 3:**
```java
Attributes attributes = new Attributes();
attributes.put("checked", "CHECKED");
Attribute attribute = attributes.iterator().next();

assertEquals("checked", attribute.html());
assertEquals(" checked", attributes.html());  // fails; output is ' checked="CHECKED"'
```

`Attribute.html()` uses a case-insensitive comparison when comparing the attribute key to its value. `Attributes.html()` uses a case-sensitive comparison.

@jhy: I'd be happy to create a pull request to fix the issues. But I'd like your opinion on what the future behavior should be. My guess is that by now many people depend on arbitrary attributes without value being treated like a boolean attribute in the output. So using the list of known boolean attributes to format unknown attributes might not be the best idea. However, we could use it to make sure jsoup never outputs an explicit value for the attributes in that list.

**Comment by jhy** [comment]
@cketti, thanks for the investigation, and sorry for my late reply. If you still want to fix this, that would be great. 

My take is the best outcome would be:
* if the attribute has no value, output it like a boolean attribute
* I think if the attribute value is explicit, and different to the attribute name, we should emit the value regardless of if we know it should be a boolean attribute. My reasoning is that otherwise there could be data loss, maybe the user didn't know it was supposed to be boolean and put something there deliberatly

Also, I wonder if setting a known boolean attribute value to null should be considered as removing the attribute?

What are your thoughts?
