### ISSUE TITLE
self-closing tag add new close tag

### ISSUE THREAD

**Issue by anthonykashkin** [jhy/jsoup#1037]
for example :
```
<div class="root"> 
     <div class="subroot"> 
          <div class="separator"> 
              <div class="a"/></div> 
              <div class="b"></div> 
          </div> 
  </div>  

```
jsoup makes
 ```
<div class="root"> 
     <div class="subroot"> 
        <div class="separator"> 
             <div class="a"> </div> 
        </div> 
        <div class="b"></div> 
   </div> 
  </div>  
```

In HTML5 self-closing should be ignored. Jsoup add new` </div> `and break DOM structure.  I'm try it in firefox and chrome, tag isn't added.

**Comment by jhy** [comment]
See also #548

**Comment by jhy** [comment]
The issue here is that we are allowing known tags that are not void to be self closing, but the HTML spec says they can't be. However in practice, when jsoup enforced this, lots of people ran into problems. Realistically I don't see why the spec is like this as the author's intent is clear - to create an empty block (or script or whatever). Not support self-closing scripts in particular causes very bad parses.

Potentially a solution to this would be to only support self-closing on known self-closing tags, and additionally allow the user to toggle the self-closing support bit on tags (in other words, let the jsoup user define what tags they want to be self closing, and add div, script, etc to the default list)
