### ISSUE TITLE
Not parsing <body> from HTML document

### ISSUE THREAD

**Issue by steven-frdm** [jhy/jsoup#1118]
I was having trouble parsing the followin url with JSoup:

https://www.cnn.com/2015/05/15/world/thailand-pm-on-fishing-slavery/index.html

I also tried it on try.jsoup.org and got the same results, the body element  parses as empty.

I didn't see a similar issue already filed. 

Thanks!

**Comment by jhy** [comment]
The issue here is that the HTML source is a bit of a dog's breakfast, and there's just under two megabytes of style and script content embedded in the head before the body. Jsoup defaults to limiting the amount read from a URL to 1MB, in an attempt to safeguard against trying to parse images etc. When I started writing this library years ago that seemed like a sensible default, but in today's race to the bottom of terrible performance, perhaps it's too small.

Anyway, just set use [.maxBodySize(0)](https://jsoup.org/apidocs/org/jsoup/Connection.html#maxBodySize-int-) and it works fine.

Example code that prints out the actual few K of text content:

            Document doc = Jsoup.connect("https://www.cnn.com/2015/05/15/world/thailand-pm-on-fishing-slavery/index.html")
                .maxBodySize(0)
                .get();
            System.out.println(doc.select("div.zn-body__paragraph"));

**Comment by steven-frdm** [comment]
Thanks @jhy
