### ISSUE TITLE
抓取gb2312的编码的网站时，部分字符会存在乱码问题

### ISSUE THREAD

**Issue by zh1181500972** [jhy/jsoup#1133]
```java
Document document = Jsoup.connect("http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/45/14/25/451425202.html").get();
Elements elements = document.getElementsByClass("villagetr");
System.out.println(elements);
System.out.println(elements.text());
```
网页上的结果
![image](https://user-images.githubusercontent.com/21984732/46777698-f4005c00-cd42-11e8-852b-b001bc63ebb4.png)
抓取下来的结果
![image](https://user-images.githubusercontent.com/21984732/46777747-31fd8000-cd43-11e8-86ff-65bb99c886af.png)
提取到的数据
![image](https://user-images.githubusercontent.com/21984732/46777763-417cc900-cd43-11e8-8d6c-c35376cc51c4.png)
，
问题造成的原因，因为gb2312包含的字符不全，导致部分汉字无法解析，应该使用gbk的编码去解析字符

**Comment by zh1181500972** [comment]
使用版本为1.11.3

**Comment by aacgn** [comment]
Please, write in english.

**Comment by bluetata** [comment]
你使用jsoup解析的时候应该指定GBK来解析它

**Comment by bluetata** [comment]
I translate @zh1181500972 's en to English :
> when @zh1181500972 crawl a gb2312 encoding website, part of the characters will have a messy code problem

cn: 首先可以排除是Jsoup的问题，我在本地已经测试该网站，直接使用GBK编码，解析出来的源码没有任何编码问题：
en: First of all, we can eliminate the problem is occurred by Jsoup. I have tested the website locally and directly used GBK coding. The parsed source has no any encoding problem:

![image](https://user-images.githubusercontent.com/25427352/48932695-328b5800-ef38-11e8-99be-8713699e9189.png)

@jhy so I thank that issue can be closed.

**Comment by jhy** [comment]
@bluetata thanks
