### ISSUE TITLE
For XML output, the default value for outputSetting().prettyPrint() should be false

### ISSUE THREAD

**Issue by danspeck** [jhy/jsoup#1168]
Jsoup.parse() by default creates a document with prettyPrint() enabled. Pretty printing html/xml introduces spurious whitespace characters in the output. The default should be to preserve the document structure (including character data) as much as possible so I believe the default for prettyPrint() should be false.

**Comment by farshidce** [comment]
instead of setting it to false would it be possible to allow the parse method to accept "outputsettings" as parameter so that the user can override default values ?
I can work on PR if this approach seems reasonable

**Comment by danspeck** [comment]
I don't think that is a good idea as it puts the burden on the user to know that by default Jsoup will parse a document in an unsafe way (i.e., will introduce spurious whitespace nodes). "Pretty printing" an XML document without knowledge of the DTD/Schema is dangerous.

**Comment by nemesis06** [comment]
I'm new to Open Source, but I could try to work on that.

**Comment by jhy** [comment]
For HTML, I prefer to keep pretty-printing defaulted on. I believe most people prefer it on as a way of making the HTML more readable and accessible.

For XML I am more inclined, and the change would be simple (in https://github.com/jhy/jsoup/blob/979d5dd744b7cd30319965743b8a62269ba7845b/src/main/java/org/jsoup/parser/XmlTreeBuilder.java#L33)

I disagree with the notion that jsoup is parsing it in an unsafe way. All whitespace is preserved (apart  from the runup at the start of HTML, which is per the spec). Pretty-printing is what happens when someone outputs the content. And the Output Settings have been in jsoup for a long time and I think are well documented. Happy to take suggestions or a PR on improving the visibility / impact of what the settings do.

**Comment by danspeck** [comment]
Perhaps my phrasing was incorrect when I said that jsoup parses a document in an unsafe way. I am most concerned with the validity of serialized XML. If the default output option for XML documents was to not prettyprint I think that would be fine.

**Comment by sniffertine** [comment]
I agree to this request. In my understanding this should be working per default

`assertEquals("before <br> after", Jsoup.clean("before <br> after", Whitelist.basic()));`

**Comment by jhy** [comment]
@danspeck yes I agree with your point for XML. Update should be to have the default in XML be false.

@sniffertine I don't agree - see notes above on my desire for the default of HTML to be pretty printed. I don't see any promises in docs that cleaning is a no-op round-trip, and am happy to correct any if I have missed.

**Comment by sniffertine** [comment]
@jhy I understand that. For me it was quite irritating that a clean operation was adding something.

**Comment by jhy** [comment]
@sniffertine definitely agree that if you don't want it and it's not what you expected, it'll be irritating! We need to fix the related issue that output settings on the input document are not passed to the cleaned output.

**Comment by jhy** [comment]
Thanks, this is done in 20797a47313b115eb220f4df74d39da9de94f5e0
