### ISSUE TITLE
TextNode content remains empty while iterating through nodes

### ISSUE THREAD

**Issue by Flameborn** [jhy/jsoup#1170]
I am using the currently latest Jsoup, 1.11.3, via Kotlin.

Sample HTML, though the issue occurs with any file:

```
<html><body>
<div>test<p>test 2</p>test 3</div>
</body></html>
```

Kotlin code, via script mode. Use *kotlinc -cp jsoup-1.11.3.jar -script script.kts file.htm* to run.

```
import org.jsoup.*
import org.jsoup.nodes.*
import java.io.File

val file = File(args[0])
val document = Jsoup.parse(file, "UTF-8")

for (node: Node in document.body().childNodes()) {
	if (node is Element) {
		println("element: ${node.tagName()}")
	}

	if (node is TextNode) {
		println("textNode ${node.text()}")
	}
}
```

Returned nodes: textNode, div, textNode. The textNodes do not contain the expected text, apart from whitespace, they are blank.

Expected result: div, textNode test, p, textNode test 2, textNode test 3

**Comment by jhy** [comment]
It took me a bit to understand the problem here. TextNodes definitely have text() content directly after the parse. Iterating them does not do anything special to leave them uncontented.

The problem here is that in your sample code, `document.body().childNodes()` only contains one node -- the div. #childNodes() as documented returns the child nodes of an element. It doesn't descend into all the grand-children and deeper.

Would suggest using the Traversor to walk all nodes if that's what you're after. Or see the added test case for a simple example using getAllElements and then iterating nodes (but has some redundancy over using a Traversor).
