### ISSUE TITLE
OGP: can not get all "meta" tags

### ISSUE THREAD

**Issue by zhujunhua2012** [jhy/jsoup#1206]
```
String url = "http://news.tom.com/201904/4008966634.html";
Document document = Jsoup.connect(url).timeout(3000).get();
Element head = document.head();
Elements metas = head.getElementsByTag("meta");
````
There're only two meta elements, 12 meta elements acturally.
The head element wil not contains all meta tags, like `<meta property="og:type" content="news"/>`.

because of some comment in the html?

**Comment by laxika** [comment]
I think because there is a span in the head: `<span class="spinner-loader" id="loadingimg">Loading&#8230;</span>`. That's totally wrong. 

There are two meta elements above it. JSoup can parse those but throw away the rest as invalid.

**Comment by jhy** [comment]
Yes, like @laxika mentioned. The `span` tag there in the head will kick the parser into treating the following elements as body tags. jsoup follows the HTML5 spec, and Chrome et al do the same.

Just do something like `document.select("meta")` so that it doesn't matter if the content is in the head or the body.

Also, would suggest asking usage questions on StackOverflow. This isn't a bug.

See https://try.jsoup.org/~WZP0r_8KoqfMamRYt-Hzi_rly4g for an example.

**Comment by zhujunhua2012** [comment]
@jhy @laxika thx, `document.select("meta")` worked.
