### ISSUE TITLE
Some characters are escaped and some characters are not escaped

### ISSUE THREAD

**Issue by HanochLzd** [jhy/jsoup#1233]
version: 1.9.2

`String content = "test & ü Ü ¥ >";`
`Jsoup.clean(content, "", whitelist, outputSettings.escapeMode(Entities.EscapeMode.base));`
 `output: test &amp; ü Ü ¥ &gt; `
Some characters are escaped and some characters are not escaped,why?

**Comment by jhy** [comment]
Because those characters don't need to be escaped; they can be encoded in UTF8, and they have no meaning in HTML that would lead them to be escaped, unlike < and &.

If you want ascii mode, put the output characterset to "ascii". 

https://jsoup.org/apidocs/org/jsoup/nodes/Document.OutputSettings.html#charset-java.lang.String-
