### ISSUE TITLE
Why does emoji length change after Jsoup.parse().text()?

### ISSUE THREAD

**Issue by Pyohwan** [jhy/jsoup#1269]
Hello.
I using Java.
I want extract text only from Html.
If input emoji, length change after executed `Jsoup.parse().text()`.
Why is this?

* gradle
```
implementation("org.apache.tika:tika-parsers:1.22")
```
* sample
```java
    @Test
    public void stripHtmlTag() {
        String sampleHtmlTag = "\uD83C\uDFC3\u200D♀️\uD83C\uDFC3\u200D♂️\uD83D\uDEB4\u200D♀️\uD83D\uDEB4\u200D♂️";

        System.out.println("origin string length : " + sampleHtmlTag.length());
        System.out.println("after parse length : " + Jsoup.parse(sampleHtmlTag).text().length());
    }
```
* result
```
origin string length : 20
after parse length : 16
```

**Comment by frostblazergit** [comment]
try `Jsoup.parse(sampleHtmlTag).wholeText().length()`

function call chain:
`org.jsoup.nodes.Element#text()` ->
`org.jsoup.nodes.Element#appendNormalisedText` ->
`org.jsoup.helper.StringUtil#appendNormalisedWhitespace` ->
`org.jsoup.helper.StringUtil#isInvisibleChar` ->
`org.jsoup.helper.StringUtil#isInvisibleChar`

![image](https://user-images.githubusercontent.com/48089979/67924421-94921a00-fbeb-11e9-8334-cb38aa098674.png)

**Comment by jhy** [comment]
Hmmm. The issue here I think is that we normalize text from the DOM and try to remove invisible characters so that the output of text() is cleaner, and text matching selectors work more reliably. However the zero width joiner is used as a modifier, and not the same as a zero width space (optional break) which was the original intent of the normalizer. Would make sense to exclude those from normalization.
