### ISSUE TITLE
Why TokenQueue is located in parser package?

### ISSUE THREAD

**Issue by hsebs** [jhy/jsoup#1282]
TokenQueue is not related to the others in the parser package.

It seems like that someone thinks TokenQueue is related to Tokenizer and moves it into parser package. 

But TokenQueue is not related to Tokenizer.

**Comment by dota17** [comment]
From the jsoup source code perspective, TokenQueue has nothing to do with html parsing. But in the parse Selector, jsoup uses TokenQueue for character processing.
 I think the author put it in the parse package probably because Its role is to parse select characters, so he put it in the parse package.
```
    /**
     * Parse a CSS query into an Evaluator.
     * @param query CSS query
     * @return Evaluator
     */
    public static Evaluator parse(String query) {
        try {
            QueryParser p = new QueryParser(query);
            return p.parse();
        } catch (IllegalArgumentException e) {
            throw new Selector.SelectorParseException(e.getMessage());
        }
    }
```

**Comment by hsebs** [comment]
As you said, TokenQueue parses characters. 
But its purpose seems not to organize the data, but to find a value.

So I think TokenQueue should be placed in the Select package.
