### ISSUE TITLE
Jsoup.parse() generate bad HTML content in script tags with "</script>" word inside

### ISSUE THREAD

**Issue by Vegeeto** [jhy/jsoup#1299]
When a script content contains a HTML variable with "<script>" tags, obtained content by Element.html() is not correct.

HTML Example:
`<script>var html = "<script>console.log('Test');</script><div>Example</div>";</script>`

The result of calling Jsoup.parse() is:
```
<html>
 <head></head>
 <body> 
  <script>var html = "<script>console.log('Test');</script>
  <div>
   Example
  </div>";   
 </body>
</html>

```
Here, parser has detected the end script tag inside HTML variable as the end of main script tag.
And selecting script element, the output for html() is:
`<script>var html = "<script>console.log('Test');</script>`

The expected result is obtain all content:
`<script>var html = "<script>console.log('Test');</script><div>Example</div>";</script>`

**Comment by jhy** [comment]
That's the expected behaviour per the HTML spec, and it works the same as Chrome (which you can see by creating that file, opening in the browser, hitting Inspect, and looking at the parse tree).

The age-old workaround is to break the psuedo script tag up. See e.g. https://stackoverflow.com/a/33969575/153184

**Comment by Vegeeto** [comment]
Thank you very much!
