### ISSUE TITLE
Improove Javadoc to tell if inputstream of parse is closed or not

### ISSUE THREAD

**Issue by enexusde** [jhy/jsoup#1340]
Many methods that allows instreams as parameter exposes infos about closing the stream. Example:
Properties#load:
- The specified stream remains open after this method returns.

This information is very usefull. I miss that in Jsoup.parse();

After intensive inspection of the sourcecode I was able to find out that the instream is not closed. To avoid this inspection-work the documentation should be improoved to having this line:
- The specified stream remains open after this method returns.

Kind regards

**Comment by jhy** [comment]
I took a look at this - a couple of points:
1 - the input stream is actually closed, in the data load method
2 - we can't guarantee that it is closed, even though the internal methods close it in a finally(), because there's a constructor which theoretically can throw an exception such as an OOM, leaving the input stream open
3 - close is OK to be called multiple times and the caller should put these in a try / finally anyway (see 2)

For that, I don't think it makes sense to add it to the docs.
