### ISSUE TITLE
Redundant whitespace appears on wrapping into a div

### ISSUE THREAD

**Issue by omotnyk** [jhy/jsoup#1401]
Basically, I just want to wrap a text into **div** but the whitespace appears right after the opening tag. This is not critical but appending the whitespace is weird. See the screenshot:
![image](https://user-images.githubusercontent.com/62619912/84534788-3dad0100-acf3-11ea-8fb7-3946b4069f18.png)

**Comment by jhy** [comment]
The wrap function is not the cause here. You are looking at the pretty-printed output of the element, which at runtime adds newlines and indents to div tags. They're not "real" textnodes in the DOM.

If you don't want pretty printing, you can disable that on the Document Output Settings.

See e.g. here with it off:
http://try.jsoup.org/~5SzjZkN6afGmypySbXYARrTzx1Q
