### ISSUE TITLE
Childs of <template> should be a document fragment

### ISSUE THREAD

**Issue by gerdriesselmann** [jhy/jsoup#1409]
The HTML5 living standard states regarding the template element (https://html.spec.whatwg.org/multipage/scripting.html#the-template-element):

> The template contents of a template element are not children of the element itself.

When parsing the following HTML:

```
<!DOCTYPE html>
<html>
<body>
  <template id=a><p>Test</p></template>
</body>
</html>
```

I therefor would expect a DOM similar to this:

```
template (DOMElement)
   #DocumentFragement
       p (DOMElement)
```

This is the way Chromium presents it in dev tools

![image](https://user-images.githubusercontent.com/940768/85845838-32eb7500-b7a5-11ea-8f55-f9de8f7532e8.png)

Alternatively, having no children at all seems also OK. I'm not sure how to interpret the standard here.

However, JSoup return this DOM tree:

```
template (DOMElement)
    p (DOMElement)
```

The p element is placed as a child beneath the template tag, which I think violates the HTML5 specification.

**Comment by gerdriesselmann** [comment]
I wrote a little JavaScript to see how Browsers handle this, and bot Firefox and Chrome return an empty child list:

```
<!DOCTYPE html>
<html>
<body>
  <template id=a><p>Test</p></template>
  <script type=text/javascript>
    let t = document.getElementById("a");
    console.log(t.tagName);
    console.log(t.childNodes.length);
  </script>
</body>
</html>
```

Both browser output

```
TEMPLATE
0
```

**Comment by bartektartanus** [comment]
Any progress on this issue?

**Comment by jhy** [comment]
I'm not sure what the best approach is here.

What would be the benefit of making it return an empty list be though -- then you can't round trip HTML that includes template tags.

What is the use case that you're trying to implement, where the current approach causes a problem?

**Comment by bartektartanus** [comment]
I want to parse, validate and modify HTML fragments, which are not necessarily full HTML page. For example I have just single table row:
```html
<tr>
  <td><img src="example.png"/></td>
</tr>
```
Parsing this using `Jsoup.parse` or `parseBodyFragment` removes this `<tr>` tag as they are not valid outside `<table>`. Wrapping it around `<template>` tag should help.

**Comment by jhy** [comment]
OK, makes sense. For that wouldn't it be better to make parseBodyFragment not conform the HTML TRs though and just leave them alone (or some other similar approach).

If we make it work per @bartektartanus your first suggestion (treat it as a new fragment element type), and don't make changes to parseBodyFragment, you're going to get the same issue. And if we just update parseBodyFragment, then you don't need to manually wrap in templates.

If we change it to @gerdriesselmann's indication of how browser javascript impls do - then the content is just being lost, so that seems a no-go.

@gerdriesselmann what was your use case? Trying to make sure we fix this wholistically.

**Comment by gerdriesselmann** [comment]
We operate a web site crawler that both validates and extracts information from out customer's websites. They use it to detect problems and improve their sites.

This bug affects us in two ways:

1. Template content is processed and may trigger incorrect warnings. Think of a an anchor tag with a placeholder as "href"-attribute like <a href="%s">. This would cause a warning about an invalid URL, since "%s" is not a valid URL encoding. 
2.  We allow our customers to provide XPath queries to validate their webpages. These queries should not get confused by <template>.

As far as I understand the DOM specification, <template> tags are represented using a special HTMLTemplateElement class, which provides an additional "content" attribute which returns a DocumentFragment containing the child elements. Additionally, the child node list of a <template> tag is indeed empty. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement

This would require adding both a DocumentFragment and HTMLTemplateElement to JSoup. I presume this would amount to quite some work.

On the other it would solve both our and @bartektartanus problems:

1. Template content is invisible to parsing (if this uses iterating over children)
2. Template content is invisible to XPath (for the same reasons)
3. Parsing rules can be less strict for a DocumentTemplate, so e.g. a <tr> without a <table> is accepted.

**Comment by bartektartanus** [comment]
@jhy - Changing `parseBodyFragment` implementation to one that does not change HTML sounds good to me! 
To be honest that's how I expected it to work before I first used it. ;)

**Comment by jhy** [comment]
Thanks for the context, makes sense. On the point about an empty node list - I think that will make sense only if we implement a HtmlTemplateElement and DocFragment (which for your usecase certainly looks like the right path). Until that's implemented I generally think it's better to leave it as it is - as a workaround for now you could just do something like `doc.select("template").remove()` I think. However others who need the content available in some way can extract the content.

This idea is somewhat similar to how we handle `noscript`  - the parser goes into a different mode and handles everything inside as plain data. We get complaints about it from time to time (because to some it's unexpected behavior) but overall I believe it's the right approach.

**Comment by gerdriesselmann** [comment]
@jhy Fine with this. We indeed use a workaround quite similar to your suggestion.

**Comment by bartektartanus** [comment]
@jhy Any (even rough) estimation on when can we expect this feature? :) Currently this is critical feature for us and I want to know if we can wait or should start looking for some temporary work-around.

**Comment by jhy** [comment]
@bartektartanus, no

**Comment by jhy** [comment]
Tracking issue for adding parse support for template: #1630 

I'm erring to implement the parsing rules of the spec, but not of wrapping the nodes in a new document fragment. So the tree will be preserved / supported, but they will still be visible to the CSS / XPath selectors. Jsoup is not a script-enabled browser and so the need to put children into a document fragment is not there.

For the purpose of data extraction, people are going to expect to write a standard selector and find content within a template (when called on the document). I don't want people to have to do a select to find a template, and then another to find content within that. I think that will be a pain and quite surprising to user.

Will be able to implement template filling with .unwrap, .clone, .append etc.
