### ISSUE TITLE
Cleaner copies the body to the new shell if body is in whitelist

### ISSUE THREAD

**Issue by sebhofmann** [jhy/jsoup#1416]
If you have a Document and use a Cleaner with a Whitelist which contains body, then the body outer html will be copied to the new body, resulting in `<body><body>...</body></body>.`

**Comment by sebhofmann** [comment]
Code to Reproduce:   
```
public static void main(String[] args) {
        final Document test = Jsoup.parse("<p>test</p>");
        final Whitelist whitelist = Whitelist.none().addTags("body", "p");
        final Document result = new Cleaner(whitelist).clean(test);
        System.out.println(result.html());
    }
```

Expected Result:
```
<html>
 <head></head>
 <body>
   <p>test</p>
 </body>
</html>
```

Actual Result:
```
<html>
 <head></head>
 <body>
  <body>
   <p>test</p>
  </body>
 </body>
</html>
```

**Comment by pas-dag** [comment]
I ran into this problem when upgrading from 1.4.1.  A quick binary search reveals 1.7.1 is the last version that doesn't have this issue, and it was introduced in 1.7.2.

**Comment by jhy** [comment]
Can you explain a bit more about why you're adding `body` to the safelist?

The definition of that tag list is that these are what we're going to allow into the body of the doc. 

Asking because I think there must be something more to it, otherwise you'd have just left the body tag out of the safelist. And a simple special casing to just clean it out doesn't seem like what you're after.

**Comment by jhy** [comment]
(Closing due to no response to my Q; please feel free to reopen with details on the use case.)
