### ISSUE TITLE
Element.hasClass ignores html strict mode

### ISSUE THREAD

**Issue by evaknin** [jhy/jsoup#1446]
Hi,
Jsoup ignores case sensitive class selector.
This happens regardless if we use strict html mode or not (&lt;!DOCTYPE html>).
It causes different behaviour from a browser behaviour when using strict mode.

For example:
&lt;!DOCTYPE html>
&lt;html>&lt;head>&lt;style type="text/css">
.c1{	font-size:44px;  }
.C1{    color:red;  }
&lt;/style>&lt;/head>&lt;body>
&lt;div class="c1">
Some text
&lt;/div>&lt;/body>&lt;/html>

The following will fetch the div, although the c is in lowercase in the div:
document.select(".C1");

My findings:
The class evaluator matches method calls Element.hasClass.
Element.has class checks for a match - ignoring the case sensitive.

**Comment by LIKP0** [comment]
Hello! I have reproduced the bug and I will try to fix it.
```
public static void main(String[] args) throws IOException {
        String path = "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <style type=\"text/css\">\n" +
                "        .c1 {\n" +
                "            font-size: 44px;\n" +
                "        }\n" +
                "\n" +
                "        .C1 {\n" +
                "            color: #ffa578;\n" +
                "        }\n" +
                "    </style>\n" +
                "</head>\n" +
                "<body>\n" +
                "<div class=\"c1\">\n" +
                "    Some text\n" +
                "</div>\n" +
                "</body>\n" +
                "</html>";
        Document doc = Jsoup.parse(path);
        System.out.println(doc.select("[class=C1]").get(0).text());
        System.out.println(doc.select("[class=c1]").get(0).text());
    }

```

**Comment by LIKP0** [comment]
Excuse me. I have reproduced the behaviour by:
```
public static void main(String[] args) throws IOException {
        String path = "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <style type=\"text/css\">\n" +
                "        .c1 {\n" +
                "            font-size: 44px;\n" +
                "        }\n" +
                "\n" +
                "        .C1 {\n" +
                "            color: #ffa578;\n" +
                "        }\n" +
                "    </style>\n" +
                "</head>\n" +
                "<body>\n" +
                "<div class=\"c1\">\n" +
                "    Some text\n" +
                "</div>\n" +
                "</body>\n" +
                "</html>";
        Document doc = Jsoup.parse(path);
        System.out.println(doc.select("[class=C1]").get(0).text());
        System.out.println(doc.select("[class=c1]").get(0).text());
    }
```
Could you tell me how to use html strict mode so I can test and add some features for Jsoup.select()?

**Comment by evaknin** [comment]
Hi,
In html5, we set strict mode by adding <!DOCTYPE html> at the beginning of the html.
If we remove it, we don't use strict mode.

**Comment by Ryderxxx** [comment]
Hi,
I think jsoup currently does not support case-sensitive select() and does not depend on whether it is html strict mode.
from [here](https://jsoup.org/apidocs/org/jsoup/select/Selector.html) you can see that selectors in jsoup are **case insensitive**.

For simplicity, maybe you can do text replacement before select, and replace the uppercase or lowercase search content with different content to eliminate conflicts, or you can nest another case sensitive method after selection.

There is no doubt that your findings are correct. In source code of jsoup 1.13.1 (the latest version so far), if we change the 1374th line of Element.java from "return className.equalsIgnoreCase(classAttr);" to "return className.equals(classAttr);" then the problem with the example you gave is solved. Class ".c1" with a lowercase c in it will not be selected by document.select(".C1"); any more.

If we want to solve this problem completely, we need to add an **case sensitive** option to the selectors in jsoup. Due to default parameters are not supported in Java, and for not to distrubing old funtions, overloading the hasxxx methods seems a good solution.

For example:

    public boolean hasClass(String className) {
        return this.hasClass(className, false);
    }

    public boolean hasClass(String className, boolean caseSensitive) {
        //some code here

        if (len == wantLen) {
            if(caseSensitive)
                return className.equals(classAttr);
            return className.equalsIgnoreCase(classAttr);
        }

        //some code here
        }
    }

But then a branch of methods need to be modified like this, since the methods are nested and we need to pass the boolean value from head to tail. This will make jsoup more complex, I'm not sure if it will bring some bad effects. 

Also, as far as I know, HTML class names are case-sensitive, while CSS selectors are generally case-insensitive. My suggestion is that we should always write code case sensitively.

**Comment by Ryderxxx** [comment]
I have tried to fix this issue, following is my pull request. Now you can case-sensitively select classes with select(".classname", true) if you want. #1527

**Comment by Ryderxxx** [comment]
#1527

**Comment by Ryderxxx** [comment]
#1527

**Comment by Ryderxxx** [comment]
I have tried to fix this issue, following is my pull request. #1527 
Now you can case-sensitively select classes with .select(".classname", true) if you want.

**Comment by Ryderxxx** [comment]
[Here](https://github.com/Ryderxxx/jsoup)‘s the code. Hope this helps you.

**Comment by evaknin** [comment]
Great.
Thanks :)

**Comment by Ryderxxx** [comment]
You're welcome! You can also write like this to automatically determine whether to use strict mode.
```
        boolean htmlStrictMode;
        try{
            htmlStrictMode = doc.documentType().name().equals("html");
        }catch (NullPointerException e) {
            htmlStrictMode = false;
        }
        doc.select(".classname", htmlStrictMode);
```

**Comment by jhy** [comment]
Thanks all for the discussion and analysis. On review, I prefer to keep these ID and class selectors case insensitive. That makes the selectors more robust to content changes, and aligns with the rest of the selectors being case insensitive.

In the rare case of case sensitivity being a requirement (that is, the page containing elements with classes (or IDs) being differentiated only by case), it's simple enough to select the desired element by iterating the `select` result and inspecting the returned element attributes.

And therefore I don't see novel value from adding an additional method here.
