### ISSUE TITLE
Jsoup.parse() API unable to retain whitespaces between 2 span tags.

### ISSUE THREAD

**Issue by SanketBhumkar** [jhy/jsoup#1463]
We are trying to parse the below html content using the Jsoup.parse() API. We want to traverse the Document returned by Jsoup.parse(). However, this parse API is not retaining the whitespaces between two span tags. Please see the attached sample which has the html content which we are trying to parse. Is there a way we can retain those white spaces? Any suggestions/help would be appreciated. Is it possible to retain these spaces through Jsoup?
[sample.txt](https://github.com/jhy/jsoup/files/5689205/sample.txt)

**Comment by jhy** [comment]
The whitespace is definitely being preserved in the DOM (as #textnodes). You can see e.g. here: https://try.jsoup.org/~DEE74jHxYKZIJQAl_tDm0iofBYk

If you are using the node traversor, you will get #textnode nodes when you visit them. Or, use the getWholeText() methods.

Otherwise, the text() methods are normalizing the whitespace (by design). You can verify with pretty print disabled.

You will probably get better results using a forum like StackOverflow for usage tips.
