### ISSUE TITLE
Empty attribute names produce invalid XML output syntax

### ISSUE THREAD

**Issue by jhy** [jhy/jsoup#1474]
As noted in this [StackOverflow question](https://stackoverflow.com/q/65633287/153184), input with an empty attribute name produces invalid XML output when using the XML syntax. (I believe it's valid but meaningless HTML..)

**Input**
```
<div ="">
```

[produces](https://try.jsoup.org/~d9Ak3YlzQMWLcWkuIc49e0_8N_4):

**XML**
```xml
<div =""=""></div>
```

**HTML**
```html
<div =""></div>
```

Need to inspect the nodes directly for XML as I'm not sure what is happening there. The HTML at least looks valid.

The expected outcome of the XML output syntax is that an XML parser can read it - so probably we need to apply the same validations as in the W3CDom convertor. Specifically, the tag name and attribute validators.

For HTML it seems syntactically valid, but maybe a better idea that we just drop attributes with no key and no value -- what could be the point of retaining them? If they have a value though, should we keep an empty name? Happy to hear from people on this.

**Comment by LIKP0** [comment]
Hello! I will try to fix it but could you give me some example codes to reproduce the bug?

**Comment by LIKP0** [comment]
Bug reproduce example:
```
public static void main(String[] args) throws IOException {
        String ht = "<div someattribute=\"somevalue\"=\"\"></div>";
        Document doc = Jsoup.parse(ht);
        doc.outputSettings().syntax(Document.OutputSettings.Syntax.xml).charset(StandardCharsets.UTF_8);//Document.java 373
        String html = doc.html();
        System.out.print(html);
}
```

**Comment by cqn2219076254** [comment]
I find that the problem is with the parser. For an input like <div ="">, the parser does not treat this as an attribute with no key and no value. Instead, it treats " ="" "as a whole as the key of attribute.

![图片](https://user-images.githubusercontent.com/71445886/115107272-64d00100-9f9c-11eb-83cd-6ee893184035.png)

XML automatically adds " ="" "  for attributes that do not have val, while HTML does not.

For example, if we input

```
<div a>
```

output of xml

```
<div a="">
```

output of html

```
<div a>
```

We can simply remove the XML auto-add ="" feature to make the results look correct. 

Or we need to rewrite parse so that it can parse attributes with no key and no val. But I think this will result in incorrect output like "< div >", because the program will not print an attribute with no key and no val, so we also need to make the program able to distinguish between "< div >" and "< div ="" >", which may be a big task.

**Comment by Ruefors** [comment]
Hello,I found that when parsing the parser treats ="" as attribute name.

So while building the xml DOM tree it completes the value to a null string

```
<div =""="">
```

In my opinion, since the value of attribute name is empty, does this result of parsing seem more reasonable?

```
<div></div>
```

**Comment by jhy** [comment]
Had another look and confirmed that the current jsoup parsing of this is correct per the spec, and aligns with chromium. That's odd, but better to stick to the spec here and clean up the XML serializer I think.

So the fix should be particularly to update just the XML serializer and test for attribute XML validity, similarly (or ideally sharing code with) the W3CDom util class.

**Comment by jhy** [comment]
OK, attribute names are now normalized & validated correctly for the specific output syntax (HTML or XML). Previously, syntactically invalid attribute names could be output by the html() methods. Such attributes are still  available in the DOM, and will be normalized if possible on output.
