### ISSUE TITLE
img src is filtered out when using cleaner

### ISSUE THREAD

**Issue by francismartens318** [jhy/jsoup#1484]
I have been looking for a duplicate, but can't find it.
There is something wrong with the clean method - probably I'm missing something
Using Jsoup 1.13.1, Jsoup.clean(..., Whitelist.basicWithImages()) cleans out the src attribute

Following assertion fails

> String htmlText = "\<img src='aFileName.png' />"
> htmlText = Jsoup.clean(htmlText, Whitelist.basicWithImages())
> assert htmlText == "\<img src='aFileName.png' />"

Results in

Assertion failed: 
> 
> assert htmlText == "\<img src='aFileName.png' />"
>        |        |
>        '\<img>'  false
> 

PS.  I will convert to safelist once 1.14.1 is released

**Comment by jhy** [comment]
Hi,

This happens because the `src` attribute policy in the `basicWithImages` safelist requires that the link points to a `http` or `https` URL. As the attribute in your example is relative, but no base URL has been specified (on parse or in the document), the relative URL cannot be resolved to an absolute URL, so the Cleaner has no way to determine what protocol it points to, and so it drops the attribute.

To allow it through, just [specify the base URL](https://jsoup.org/apidocs/org/jsoup/Jsoup.html#clean(java.lang.String,java.lang.String,org.jsoup.safety.Safelist)) when the document is parsed:

```java
public static void main(String[] args) throws IOException {
    String htmlText = "<img src='aFileName.png' />";
    htmlText = Jsoup.clean(htmlText, "https://mysite.com/", 
            Whitelist.basicWithImages().preserveRelativeLinks(true));
    System.out.println(htmlText);
}
```

Gives us:

```html
<img src="aFileName.png">
```

(One thought for an update to the `Jsoup.clean(String, Safelist)` method (no base URI passed) would be to default the preserve relative links option to true and use a dummy base URL internally, or otherwise allow relative URLs.)

**Comment by francismartens318** [comment]
This works - thanks for the details.
Allowing relative URL's seems to be the correct path when 'preserveRelativeLinks' is true.
Jsoup rocks - I'm a fan.
