### ISSUE TITLE
Cannot get childNodes from param tag

### ISSUE THREAD

**Issue by kevinw66** [jhy/jsoup#1488]
When I use `Jsoup.parse(file, "UTF-8")` and `document.getElementsByTag("param")` to parse xml file like below. I cannot get childNodes `value` from `param` element. But when I change `param` to another name like `node`, It works.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<params config_name="params">
    <param param_code="CODE">
        <value param_value="2222"/>
    </param>
</params>
```

**Comment by jhy** [comment]
You didn't show code, but I'm guessing you're using the HTML parser, not the XML parser.

Make sure you use the XML parser when you're parsing XML. Otherwise, when parsed as HTML, nodes like `param` have special tree logic, and can't accept child nodes.

See it correctly parsed here - https://try.jsoup.org/~tccFqKd1e7R4Qw3IU-1tEguWWKk

[Javadoc](https://jsoup.org/apidocs/org/jsoup/Jsoup.html#parse(java.io.InputStream,java.lang.String,java.lang.String,org.jsoup.parser.Parser)) for supplying the XML parser.
