### ISSUE TITLE
Problem when selecting P tag

### ISSUE THREAD

**Issue by jiong-fu** [jhy/jsoup#1623]
Hello,

I am now working with the 1.14.2 version and trying to select all the P tags from a simple HTML fragment as follows.
```
Document document = Jsoup.parseBodyFragment("<p><t><p>test</p></t></p>");
document.outputSettings().prettyPrint(false);

// select all tags of specific type
document.body().select("p").forEach(System.err::println);
```
Expected result
```
<p><t><p>test</p></t></p>
<p>test</p>
```
Actual result
```
<p><t></t></p>
<p>test</p>
<p></p>
```

Just of curiosity I tried to replace all the P tags with customized C tags and it works just fine.
```
Document document = Jsoup.parseBodyFragment("<c><t><c>test</c></t></c>");
document.outputSettings().prettyPrint(false);

// select all tags of specific type
document.body().select("c").forEach(System.err::println);
```
Expected and actual result
```
<c><t><c>test</c></t></c>
<c>test</c>
```
Could you confirm whether is this an issue? Is there currently a workaround to get the expected result?

Thanks in advance,
Jiong

**Comment by jhy** [comment]
Your expected result is not the actual result because -- as you point out -- in HTML, `p` tags cannot contain other `p` tags. That allows them to have optional end-tags. So when the second `p` opener is seen it closes the first (and triggers the reinsertion algorithm to handle the now unclosed `t` when it sees the p closer, leading to the final third `p` element).

Your example with `c` elements does not have this behaviour as `c` tags aren't defined in HTML and therefore are flexible to containing other `c` tags.

You can play around with this at https://try.jsoup.org/~g-ELJssg_w5t1OddA_YgGYjJ5cA  - that will show you the parse tree and hence how selectors are going to work on it.

You can use XML mode if you don't want this HTML behavior.
