### ISSUE TITLE
Case Insensitive Search is Case Sensitive

### ISSUE THREAD

**Issue by fizik-service** [jhy/jsoup#1626]
I have a HTML file which I'm reading as string: https://pastebin.pl/view/0068acb8

Looking at the docs: https://jsoup.org/apidocs/org/jsoup/select/Selector.html
The contains should be case insensitive but from my tests it is.
I'm using version 1.14.2.
```
String str = GetFileAsString.get();
Document doc = Jsoup.parse(str);
String inner = doc.selectFirst("*:contains(test)").text();
```
returns no results

`String inner = doc.selectFirst("*:contains(Test)").text();`
Returns a single result.

I would expect both to return a single result.
Is there something I'm missing?

**Comment by jhy** [comment]
Yes you should expect it to be case insensitive. It works correctly in my test, see: https://try.jsoup.org/~vWnQyYnWmecDuvGnopd6k_bpl2o

And you would probably be better off with using a selector like `:containsOwn(test)` otherwise you'll select every parent of the element you want as well. E.g. https://try.jsoup.org/~faW_3DIAljWj_d9rN4fmu3FlEYg

I don't know what your GetFileAsString method does but I can only guess something is wrong there. Please have a go on try.jsoup.org and if you are still stuck, provide a complete minimal reproducible testcase so we can further debug.

**Comment by fizik-service** [comment]
```
Elements result = doc.getElementsContainingOwnText("Test"); // Single result
Elements result = doc.getElementsContainingOwnText("test"); // Single result
```
Both return a single result.


```
doc.selectFirst("*:contains(test)").text(); // No result
doc.selectFirst("*:contains(Test)").text(); // Single result
```
It's like the cssQuery is case sensitive when it shouldn't be.

**Comment by jhy** [comment]
Hi -- I see that you closed this, can you let us know the resolution? Did you find an issue in your code, or is there still an issue here, or?
