### ISSUE TITLE
attr("abs:src") return ""

### ISSUE THREAD

**Issue by fuzhengyin** [jhy/jsoup#1633]
when `<img src="//test.org/hello.png"/>`
use `attr("abs:src")` return `""`

**Comment by jhy** [comment]
(I updated your text so we could actually read the code you provided.)

Please make sure when you file an issue that you provide an actual code snippet so that we can reproduce and verify. In this case I can't see how you're parsing the content or what you think the bug really is.

Relative links can not be made absolute unless you provide a base URL when parsing to make the URL absolute with. You can either provide it as an argument when parsing. See all the `baseUri` arguments to the parse methods in the [jsoup ](https://jsoup.org/apidocs/org/jsoup/Jsoup.html)class.

See also the docs for the [absUrl ](https://jsoup.org/apidocs/org/jsoup/nodes/Node.html#absUrl(java.lang.String))method (which is what `abs:src` is documented as using) which explains this, and why you get an empty string if the URL cannot be made absolute.

And note that URLs of the form `//example.com/foo.html` are not absolute as they don't have a protocol defined. The protocol used must be determined from the base URL, which I don't believe you are providing. We can't guess, should it be http:, https:, ftp:, telnet:, gopher:, magnet:...?

Please confirm that it works when you supply a base URL.

**Comment by fuzhengyin** [comment]
just like this?
parse.setBaseUri("https://test.org/");
or
parse.setBaseUri("https://test.org");
Doesn't work

**Comment by fuzhengyin** [comment]
It works
Thanks
