### ISSUE TITLE
Document::location does not contain fragment identifier

### ISSUE THREAD

**Issue by mahozad** [jhy/jsoup#1686]
Hi,

It is important for me to get the fragment id of a page from jsoup *Document*s.  
Is it possible to get the URL intact as passed to the *Jsoup::connect* method?

The original URL that I pass to *Jsoup::connect* method has a fragment identifier at its end.
But *Document::location* or *Document::baseUri* do not contain the id.

For example, `https://developer.android.com/jetpack/androidx/releases/annotation`**`#annotation-1.4.0-alpha01`**
becomes `https://developer.android.com/jetpack/androidx/releases/annotation`.

**Comment by jhy** [comment]
I guess we could update Connection to remember the fragment. It's a client-side only thing and doesn't get sent to the server during the connection, hence why it's not in the location().

**Comment by mahozad** [comment]
Is there any hope for this to be fixed?

**Comment by jhy** [comment]
Sure, why not? Happy to review a PR if you want to get in there yourself.

**Comment by jhy** [comment]
I took another look at this and confirmed that the fragment is retained through `Jsoup.connect(url)` to `document.location()`, so I don't see that a change is required.

I wonder if you were seeing it removed from the URL you fetched due to a redirect for authentication or similar? The fragment is not sent server-side and doesn't survive redirects.

**Comment by mahozad** [comment]
I tried `https://developer.android.com/jetpack/androidx/releases/annotation#annotation-1.4.0-alpha01` and it does not seem to return redirect but `document.location()` does not have the fragment:

`https://developer.android.com/jetpack/androidx/releases/annotation`
