### ISSUE TITLE
select xpath with last() bug

### ISSUE THREAD

**Issue by pipicoming** [jhy/jsoup#1708]
test url: https://try.jsoup.org/~LGB7rk_atM2roavV0d-czMt3J_g
xpath: //div[@id='mp-itn']//b/a[last()]
result: should be show the last one , but show all. more info in the attach pic.
<img width="1192" alt="jsoupbug" src="https://user-images.githubusercontent.com/23277111/150102127-86a86d99-2787-424b-b948-f1f64dd42a2b.png">

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by JeffXiesk** [comment]
Hi, I just find solution of your file.
The problem is not about the last method. It may be about your query statement.

When using  " //div[@id='mp-itn']//b/a[last()] ". The result is the same as using " //div[@id='mp-itn']//b/a ".
![NO T17%1CYGNS} B9P${0XE](https://user-images.githubusercontent.com/75991596/164018807-cddd36a8-2fea-44d9-b27b-7a576ec9ce57.png)

To get the last element. It is wise to add a brackets, use "  (//div[@id='mp-itn']//b/a) [last()] " instead.
You can see the result as below. 
![_3J5(T8}3 U PKJX3OC_AV](https://user-images.githubusercontent.com/75991596/164018761-f98d3810-507f-47b9-a181-75be658b84e0.png)

**Comment by jhy** [comment]
Thanks @JeffXiesk
