### ISSUE TITLE
An attribute with a " in its name will be serialized without it

### ISSUE THREAD

**Issue by sumanth13131** [jhy/jsoup#1795]
We are facing the issue in parsing HTML with attr values that look JSON format with Jsoup1.14.3.jar . But it's parsing fine with jsoup1.13.1.jar
Jsoup version: 1.14.3

## source.html file
``` 
<html> 
 <head> 
  <title>Try jsoup</title> 
 </head> 
 <body> 
  <div class="authors authors-mosaic slot5">
   <ara-swiper template="authors" slot-type="slot5" :cards="[{" brandedcontent":null,"mediainfo":null,"id":4409516,"title":"seguir jugant amb els jocs"}]" card-class="" more="Veure'n més"> 
   </ara-swiper> 
  </div>  
 </body>
</html>
```
## Parsed output from jsoup1.13.1
```
<html> 
 <head> 
  <title>Try jsoup</title> 
 </head> 
 <body> 
  <div class="authors authors-mosaic slot5"> 
   <ara-swiper template="authors" slot-type="slot5" :cards="[{" brandedcontent":null,"mediainfo":null,"id":4409516,"title":"seguir jugant amb els jocs"}]"  card-class="" more="Veure'n més"> 
   </ara-swiper> 
  </div>  
 </body>
</html> 
```
## Parsed output from jsoup1.14.3
```
<html> 
 <head> 
  <title>Try jsoup</title> 
 </head> 
 <body> 
  <div class="authors authors-mosaic slot5"> 
   <ara-swiper template="authors" slot-type="slot5" :cards="[{" brandedcontent:null,mediainfo:null,id:4409516,title:seguir jugant amb els jocs}] card-class="" more="Veure'n més"> 
   </ara-swiper> 
  </div>  
 </body>
</html> 
```
## Difference found
Jsoup 1.13.1    <span style="background-color: #f55d42" > :cards="[{" brandedcontent":null,"mediainfo":null,"id":4409516,"title":"seguir jugant amb els jocs"}]" </span>
Jsoup 1.14.3    <span style="background-color: #f55d42" > :cards="[{" brandedcontent:null,mediainfo:null,id:4409516,title:seguir jugant amb els jocs}]  </span>

## Issue
@jhy 
In above ``` brandedcontent:null,mediainfo:null,id:4409516,title:seguir jugant amb els jocs}]``` treating as attr_name and  truncating at certain length.

**Comment by jhy** [comment]
Thanks for providing a sample. I will take a look - first guess is that this super-sized attribute is overrunning the buffer in CharacterReader and then is exiting the attribute value state incorrectly before re-buffering.

**Comment by jhy** [comment]
OK, with your edits I see that you are looking at something different to what I was looking at.

What you are getting is an outcome of the very invalid attribute content. The actual parsed content looks like this in the DOM (and is the same as how Google Chrome parses it, for reference):
```HTML
 <a :cards="[{" brandedcontent":null,"mediainfo":null,"id":4409516,"title":"seguir jugant amb els jocs"}]" 
card-class="" more="Veure'n més"></a>
```

| Attribute Name | Attribute Value |
| --- | --- |
| :cards | [{ |
| brandedcontent":null,"mediainfo":null,"id":4409516,"title":"seguir |
| jugant |
| amb | |
| els | |
| jocs"}]" | |
| card-class | |
| more | Veure'n mÃŠs |

The attribute parsing here is "correct" in the sense of that's per the HTML5 spec, and that's the standard approach to parsing this garbage.

The issue / difference you are seeing between 1.13 and 1.14 we started to normalize attribute names on output and remove quote characters: #1474.

A change may be to allow those quote characters to be output in the middle of attribute names (and still drop those "empty" attributes that the bug was initially focused on). I'm not yet sure the best approach as that can cause misleading HTML output. Either way it's not causing a problem in the parse, and the DOM is correct currently.

**Comment by jhy** [comment]
(Closing, as this works to spec - might review other output options at another time.)
