### ISSUE TITLE
Version is missing in package meta-inf

### ISSUE THREAD

**Issue by gertjanal** [jhy/jsoup#1809]
For testing, it would be great to get the jsoup version at runtime.

```java
    @Test
    void testVersions() {
        System.out.println(Jsoup.class.getPackage().getSpecificationVersion());
        System.out.println(Jsoup.class.getPackage().getImplementationVersion());
        System.out.println(Jsoup.class.getPackage().getSpecificationVersion());
    }
```

Version 1.15.2 (and before) returns
```
null
null
null
```

It shouldn't be that hard: https://stackoverflow.com/questions/921667/how-do-i-add-an-implementation-version-value-to-a-jar-manifest-using-maven

**Comment by jhy** [comment]
Thanks, done

**Comment by JamoCA** [comment]
I'm using ColdFusion and Oracle JDK 11.0.15.1. I've updated jsoup to `1.15.3`, but I'm unable to programmatically determine the version.

I'm using the following CFML code to dump version and both return an `undefined` object instead of the expected string denoting the current version.  (Am I doing it incorrectly or is it not working?)

```java
jsoup = createobject("java", "org.jsoup.Jsoup");
writedump(var="#jsoup.getClass().getPackage().getSpecificationVersion()#");
writedump(var="#jsoup.getClass().getPackage().getImplementationVersion()#");
```

**Comment by jhy** [comment]
@JamoCA I just tested, and this works in Java. Not sure how that translates to ColdFusion though.

```java
Package jsoupPackage = Jsoup.class.getPackage();
System.out.println(jsoupPackage.getImplementationTitle());
System.out.println(jsoupPackage.getImplementationVersion());
```

Produces:
```text
jsoup Java HTML Parser
1.15.3
```

**Comment by JamoCA** [comment]
I've spent a while researching this and it continues to return `undefined`. I have to add try/catch around the request in order to prevent it from crashing the process.

I started reviewing manifests of other JARs that we use in production. I noticed that PDFBox had a `Specification-Version` key in their manifest, but when dumping the object, I noticed that they also had a specific `getVersion()` method to provide the information.
https://pdfbox.apache.org/docs/2.0.2/javadocs/org/apache/pdfbox/util/Version.html

Could a `getVersion` method be added?  I believe, based on this link below, that my only workaround would be to write a routine to locate the physical path of the JAR, unzip the manifest file and parse the lines of text. (Not very optimal.)
https://stackoverflow.com/q/38204059/693068

**Comment by jhy** [comment]
I checked PDF Box's implementation of getVersion() -- it's coming from a resource file, not the manifest. Perhaps as a way to workaround the packaging issue in my edit above.

https://github.com/apache/pdfbox/blob/trunk/pdfbox/src/main/java/org/apache/pdfbox/util/Version.java
https://github.com/apache/pdfbox/blob/trunk/pdfbox/src/main/resources/org/apache/pdfbox/resources/version.properties

So, that might be a good approach. (Although I do note that jsoup used to use resource files for the named character entity definitions, and would see crashes on various Android forks as an app couldn't load jar resources on first install. Hopefully that's improved over the years...)
