### ISSUE TITLE
Jsoup br closing tag is converted into separate br tag

### ISSUE THREAD

**Issue by mykolap** [jhy/jsoup#1815]
I have html text, it is processed later by xhtml tool, and each tag should be closed, including br.
But if br has closing tag - after processing by jsoup it is converted into 2 tags, that produces 2 issues:
xhtml tool complains about not closing tags
we have 2 breaks instead of single in source

Test that shows the issue:
`    @Test`
`    void trackBugInJsoup() {`
`        final String source = "<p>text<br></br></p>";`
`        final String expectedWrong = "<p>text<br><br></p>";`
`        Document document = Jsoup.parse(source);`
`        assertThat(document.body().html()).isEqualTo(expectedWrong);`
 `   }`

**Comment by jeffthomasweb** [comment]
Thank you for including a very clear example. It's my understanding that a single `<br />` tag meets the XHTML standard  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br#technical_summary but Jsoup also produces a `<br>` tag if a single `<br />` is used in the original HTML. I'm not sure what the ideal solution for this issue is but if you find it simpler to just remove all `<br>` and `<br />` tags until a better solution is found, you could use Safelist to add and remove desired HTML tags and attributes https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/safety/Safelist.java . 
```
String cleanBrTags() throws IOException {
    //Safelist.basic() allows general HTML tags and attributes to stay in the final product. 
    //removeTags() and addTags() can be used to remove/add specific tags.
    
    Safelist listOfSafeHtml = Safelist.basic().removeTags("br");
    String htmlWithBr = "<p>text<br /></p>";
    String cleanedBasicHtmlNoBr = Jsoup.clean(htmlWithBr, listOfSafeHtml);

    return cleanedBasicHtmlNoBr;
    }
```

**Comment by mykolap** [comment]
We are also using com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer for sanitizing content.
And it transforms any <br>, closed or not closed to <br />. Doing the same would be also nice I think.
In my cause I need to traverse tree and do some modifications, for that I need Jsoup, and at the end desired result if fixed, transformed body of original source. And it works fine except issue with <br>

**Comment by jhy** [comment]
This is working as to the [HTML5 spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody):

An end tag whose tag name is "br"
[Parse error. Drop the attributes from the token, and act as described in the next entry; i.e. act as if this was a "br" start tag token with no attributes, rather than the end tag token that it actually is.

Where is this closing `</br>` tag coming from? It's not HTML - it might be simplest to change your tool to not output that.

Or, you could use the XML parser, which doesn't use the HTML5 rules and so you won't get the extra br node.

See e.g.: https://try.jsoup.org/~-xMvxwieuPmwcB5GoiVl7vqGvTA

**Comment by mykolap** [comment]
Some strange transformation, like dublicating br is not the only issue.
In this example - head content moved from head to body:
` @Test
    // https
    void anotherJsoupBug() {
        final String source = "<html><head>head content</head><body><p>text CASE<br></p></body></html>";
        final String expectedWrong = "head content\n<p>text CASE<br></p>";
        Document document = Jsoup.parse(source);
        assertThat(document.body().html()).isEqualTo(expectedWrong);
    }`

**Comment by jhy** [comment]
Yes, text content cannot appear in the head and so is always moved to the body.

If you don't want the HTML rules applied, use the Jsoup XML parser instead.

**Comment by mykolap** [comment]
My task was simple - to process everything withing body, but don't dublicate anything, and don't insert content from head into body. I still think it's wrong if something dublicated or transfering content from head to body. If something is invalid - it should be thrown away. 
I cannot use xml parser - because source content in strangely transformed, but method parseXmlFragment actually works, the only thing I have as output not document, but nodes.
And instead of document.body() I need to use this
    private List<Node> extractNodesWithinBody(List<Node> childNodes) {
        if (childNodes.isEmpty()) {
            return childNodes;
        }
        for (Node currentNode : childNodes) {
            if (currentNode instanceof Element element) {
                final String tagTame = Optional.ofNullable(element.tag()).map(Tag::getName).orElse("");
                if (StringUtils.equalsIgnoreCase(tagTame, "html")) {
                    return extractNodesWithinBody(currentNode.childNodes());
                } else if (StringUtils.equalsIgnoreCase(tagTame, "body")) {
                    return currentNode.childNodes();
                }
            }
        }
        return childNodes;
    }
And then transform nodes into text.

**Comment by jhy** [comment]
You might want to try on Stack Overflow or another support forum.
