### ISSUE TITLE
element.selectXpath unexpected behaviour.

### ISSUE THREAD

**Issue by zaurkadiev** [jhy/jsoup#1889]
Example:

![save](https://user-images.githubusercontent.com/1666740/214898824-ae441306-80f2-4137-ab94-44e52d5a6dbb.png)

Let's assume we have same elements `div1`, `div2`, `div3` with a similar inner tag structure.

If I have element `div2` and try `element.selectXpath(path)`, I have the result from `div1`. Similar with the element `div3`. If I have the element `div3` and call `element.selectXpath(path)` I have the result from `div1`.

By the way `element.select(selector)` works just as expected, `div1` selects only inside `div1` scope, `div1` inside `div1` scope, etc.

Seems like this is an issue:

Inside mentioned test case.
https://github.com/jhy/jsoup/blame/be24647192f7870da500fb83650bacafed81151f/src/test/java/org/jsoup/select/XpathTest.java#L38

`assertEquals(1, div.selectXpath("//body").size()); // the whole document is visible on the div context`

_Originally posted by @zaurkadiev in https://github.com/jhy/jsoup/issues/1856#issuecomment-1405334366_

**Comment by jhy** [comment]
Rather than a picture and a narrative, your report would be a lot better with a simple repeatable test case showing what you're trying to do, what you're getting, and what you want instead. You haven't mentioned what XPath query you are using so I can't evaluate your issue.

However - by referencing the `//body` test case, my guess is that you are using absolute queries? The `element.selectXpath()` method uses the given element as the context, but the entire DOM is still available. If you provide a relative query, it will be relative to the context element, and if you provide an absolute query, it will be absolute to the entire DOM. Hence, the test case.

See #1652 for background on this.

LMK if with that understanding your issue is resolved, otherwise please provide a simple test case.
