### ISSUE TITLE
Incorrect attribute output in xml

### ISSUE THREAD

**Issue by AugustoWYZ** [jhy/jsoup#1946]
First of all, thanks a lot for this code. It works great.
However I noticed a weird behavior. In Entities.escape this case fragment exist

```java
case '<':
    // escape when in character data or when in a xml attribute val or XML syntax; not needed in html attr val
    if (!inAttribute || escapeMode == EscapeMode.xhtml || out.syntax() == Syntax.xml)
        accum.append("&lt;");
    else
        accum.append(c);
    break;
case '>':
    if (!inAttribute)
        accum.append("&gt;");
    else
        accum.append(c);
    break;
```

I was working wtih an xml that is something like
```xml
<xml>
<sometag> sometext
<innertag>
more text
<?xmlDeclaration att1="value1" att2="&lt;val2&gt;"?>
</innertag></sometag></xml>
```

and when extracted the document as string it looks like
```xml
<xml>
<sometag> sometext
<innertag>
more text
<?xmlDeclaration att1="value1" att2="&lt;val2>"?>
</innertag></sometag></xml>
```

Is there any specifics why ">" is not considered the same as "<" for xmls?

Thanks in advance

**Comment by jhy** [comment]
Because in XML `<` must always be escaped, but `>` in an attribute does not need to be escaped. And we only escape if required.

As a tip to research these kind of questions (vs starting by calling it a bug) you can look at the history of the file and see if there's commits / bugs with details on it. E.g. in this case: visit https://github.com/jhy/jsoup/blame/master/src/main/java/org/jsoup/nodes/Entities.java, click "Blame", then look at the associated commits and issues. Relevant details are in 528d85f3a99bf3a064eb8582af0643e1cc65f206 and #1420
