### ISSUE TITLE
<li> outside of <ul>,<ol>,<menu> should trigger error

### ISSUE THREAD

**Issue by robstoll** [jhy/jsoup#2031]
according to WC3 HTML5 standard an `<li>` cannot be outside of an `<ul>`,`<ol>` or `<menu>`. Jsoup doesn't complain about it `JSoup.isValid(...)` returns true.

I would have expected jsoup complains if invalid html is provided as input. Is this a misconception on my part and jsoup is not capable to do HTML validation or is it a bug?

Another example where I would have expected jsoup to error:
```
<ul> <p>p is not allowed inside of ul, only script, template and li are allowed </p></ul>
```

**Comment by jhy** [comment]
Hi Robert,

Where are you seeing in the spec that an LI needs to be inside a UL? Per the parser spec at [A start tag whose tag name is "li"](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody:~:text=A%20start%20tag%20whose%20tag%20name%20is%20%22li%22), there's no requirement that it's in a UL / OL. It doesn't emit an error and it doesn't create an implicit OL or UL block.

Similarly for the P case - spec [here](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody:~:text=A%20start%20tag%20whose%20tag%20name%20is%20one%20of%3A%20%22address%22%2C%20%22article%22%2C%20%22aside%22%2C%20%22blockquote%22%2C%20%22center%22%2C%20%22details%22%2C%20%22dialog%22%2C%20%22dir%22%2C%20%22div%22%2C%20%22dl%22%2C%20%22fieldset%22%2C%20%22figcaption%22%2C%20%22figure%22%2C%20%22footer%22%2C%20%22header%22%2C%20%22hgroup%22%2C%20%22main%22%2C%20%22menu%22%2C%20%22nav%22%2C%20%22ol%22%2C%20%22p%22%2C%20%22search%22%2C%20%22section%22%2C%20%22summary%22%2C%20%22ul%22) does not include checks for what block it's being inserted into, just implicitly closing an existing P.

[Jsoup.isValid(html, safelist) ](https://jsoup.org/apidocs/org/jsoup/Jsoup.html#isValid(java.lang.String,org.jsoup.safety.Safelist)) will return false if anything in the input was dropped because of the Safelist settings, or there were parser errors emitted. You can also get the errors directly from the parser. So yes, jsoup can be used to validate, according to the spec's view of validity. isValid() should always be combined with taking the cleaned HTML from the Cleaner as there are still output normalizations applied.

Let me know if I've missed something in the spec that would make these specifically emit errors.

**Comment by robstoll** [comment]
sorry, that was not very precise, I updated the title and description to reflect the HTML5 spec:
https://www.w3.org/TR/2011/WD-html5-20110405/grouping-content.html#the-li-element

for instance, w3c validator (https://validator.w3.org/nu/#textarea)  complains for:
```html
<!DOCTYPE html>
<html>
<head><title>b</title></head>
<body><li></li></body>
</html>
```
but jsoup doesn't.

**Comment by jhy** [comment]
> sorry, that was not very precise, I updated the title and description to reflect the HTML5 spec:
> https://www.w3.org/TR/2011/WD-html5-20110405/grouping-content.html

That W3C spec from 2011 is out of date. The spec that jsoup follows is at  https://html.spec.whatwg.org/ (and is the "official" HTML5 spec, fwiw). Note that the popup at the bottom of the W3C link above link directs there also.

**Comment by robstoll** [comment]
interesting, didn't see that popup, thanks.  however, also this spec states the same:
https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element

I guess what you are referring to is how browers should parse, even in the presence of invalid html, to kind of have a standard behaviour to auto-close/auto-ignore elements.

**Comment by jhy** [comment]
Right, no, we don't validate against that. Just the errors that the parser emits.

Might be a nice plugin/add on to do.
