### ISSUE TITLE
Document.toString html encodes urls

### ISSUE THREAD

**Issue by robstoll** [jhy/jsoup#2033]
Consider the following:
```
Jsoup.parse("<a href=\"https://example.com?a=b&c=d\">a</a>").toString()
```
results in `https://example.com?a=b&amp;c=d`
Maybe `toString` was not designed to retrieve the Document as string and I should use something else?

**Comment by jhy** [comment]
Can you clarify why you think this is a bug? Ampersand characters in HTML output are encoded. If you want decoded text, use one of the `Element#attr(name)` methods (for attributes) or `Element#text()` for text nodes.

**Comment by robstoll** [comment]
ampersand encoding in html is good, but within urls it changes its meaning. `https://www.google.com/search?q=jsoup&tbm=isch` searches in images but `https://www.google.com/search?q=site:+bla&amp;tbm=isch` does not as the param `tbm` and `amp;tbm` are note the same

**Comment by jhy** [comment]
When the encoded HTML output produced by jsoup is parsed by a browser, it is decoded, and the URL will be correct. 

This is the correct behaviour.

**Comment by robstoll** [comment]
fantastic, wasn't aware of that, many thanks for the quick reply

**Comment by goodalex** [comment]
This issue seems to have been pointed out many times in this repo.

Case 1
Jsoup.parse("<a href=\"https://example.com?a=b&c=d\">a</a>").toString() 
should result in the following HTML -> <a href="https://example.com?a=b&c=d">a</a> -> would be correct

Case 2
Jsoup.parse("<a href=\"https://example.com?a=b&amp;c=d\">a</a>").toString() 
should result in the following HTML -> <a href="https://example.com?a=b&amp;c=d">a</a>  -> would be correct

Broken behavior
Jsoup.parse("<a href=\"https://example.com?a=b&amp;c=d\">a</a>").toString() 
resulting following HTML -> <a href="https://example.com?a=b&amp;c=d">a</a> **is a bug**

Case 1 and Case 2 are two different values. The escaping should not apply to attribute values.
How is a browser supposed to know which value was originally meant?  It's two different values.

Both are different links. **This is a bug.**
