### ISSUE TITLE
Connecting to a URL encodes a '+' in the string to %20 (blank),

### ISSUE THREAD

**Issue by billthefarmer** [jhy/jsoup#2089]
For example, `https://nextbuses.mobi/WebView/BusStopSearch/BusStopSearchResults/ll_53.91064,-0.17317~Hornsea%2c+East+Riding+of+Yorkshire?currentPage=0` becomes `https://nextbuses.mobi/WebView/BusStopSearch/BusStopSearchResults/ll_53.89802,-0.17097~Hornsea%20Freeport,%20East%20Riding%20of%20Yorkshire?currentPage=0` causing an error (android):
```
System.err: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=400, URL=[https://nextbuses.mobi/WebView/BusStopSearch/BusStopSearchResults/ll_53.89802,-0.17097~Hornsea%20Freeport,%20East%20Riding%20of%20Yorkshire?currentPage=0]
```
I am using the simplistic Jsoup method:
```java
                Document doc = Jsoup.connect(url).get();
```
If I pre-encode the '+' to '"2B", this fixes the issue. Is this intentional? Is there a better way of doing this to avoid this issue.

Edit: I am using version 1.16.1 because later versions are using `ThreadLocal.withInitial()`, which is not supported on earlier versions of android.

**Comment by jhy** [comment]
You should upgrade to the current version, as it works correctly there. Fixed in [1.16.2](https://jsoup.org/news/release-1.16.2).

See the [Readme](https://github.com/jhy/jsoup) or the [Download](https://jsoup.org/download) page for instructions on how to enable Android using the core library desugaring configuration option. It works.
