### ISSUE TITLE
Jsoup Issue: <table> tag inside <span> of <p> tags are getting unwrapped outside and empty <p> tags are created

### ISSUE THREAD

**Issue by Muthukirthan** [jhy/jsoup#2197]
Input:
```
<html>
    <head></head>
    <body>
        <p>
            <span>
                <table>
                    <tbody>
                        <tr>
                            <td><span>Hello table data</span></td>
                        </tr>
                    </tbody>
                </table>
            </span>
        </p>
    </body>
</html>

```

Jsoup output:
```
<html>
    <head></head>
    <body>
        <p>
            <span>
                </span></p><table>
                    <tbody>
                        <tr>
                            <td><span>Hello table data</span></td>
                        </tr>
                    </tbody>
                </table>
            
        <p></p>
    </body>
</html>
```

Ref link: https://try.jsoup.org/~PNrKdofSo_QE8KX2IbZKZ-xxyq0

The table tag inside span of p tag is unwrapped as next sibling of p tag. Additionally an empty p tag is created as the next sibling of the unwrapped table tag. This output is not seen in Chrome and Firefox browsers

**Comment by jhy** [comment]
Hi,

The parse you are getting is coming from the implementation of this rule:

[A start tag whose tag name is "table"](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody:~:text=last%20marker.-,A%20start%20tag%20whose%20tag%20name%20is%20%22table%22,-If%20the%20Document).

In [HtmlTreeBuilderState](https://github.com/jhy/jsoup/blob/3244429f2e5a023e8833c39acfef36237de015c8/src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java#L457-L464), we are treating the document as No Quirks, but because there is no doctype, it should be treated as Quirks, and so the `p` should not be closed when the `table` gets opened.

jsoup's doesn't currently implement Quirks Mode completely. We do go into quirks mode when parsing invalid doctypes, but don't have the expected doctype tests. Implementing that would allow this to be fixed. 

Checked in Chrome and if there is a valid doctype and so in No-Quirks mode, Chrome does parse the same as jsoup does currently:

<img width="332" alt="Screenshot 2024-09-10 at 3 19 26 PM" src="https://github.com/user-attachments/assets/78d4ea9e-c185-4a8b-84d8-ef17eb893048">

**Comment by jhy** [comment]
Thanks for reporting! Fixed.
