### ISSUE TITLE
JSoup can't handle @href

### ISSUE THREAD

**Issue by agustinuslaw** [jhy/jsoup#2231]
Is directly getting an attribute via XPath an unsupported feature in JSoup?

The example below was also tested using Google Chrome XPath in page https://commons.m.wikimedia.org/wiki/Main_Page.

```java
    @DisplayName("JSoup can't get @href XPATH directly")
    @Test
    public void jsoupHrefIssue() throws Exception {
        String url = "https://commons.m.wikimedia.org/wiki/Main_Page";

        Connection session = Jsoup.newSession()
                .timeout(5000)
                .newRequest(url);
        Document doc = session.get();

        // This XPATH exists, but JSOUP will not find @href node
        var aXpath = "//*[@id='mf-section-0']//td[@class='mainpage-actions']//a[@title='Category:Images']";
        var hreXpath = "//*[@id='mf-section-0']//td[@class='mainpage-actions']//a[@title='Category:Images']/@href";
        var link = doc.selectXpath(aXpath, Node.class).stream().findAny().orElse(null);
        var href = doc.selectXpath(hreXpath, Node.class).stream().findAny().orElse(null);

        assertNotNull(link);
        assertNotNull("/wiki/Category:Images",link.attr("href"));
        // href is null, but it shouldn't be null.
        assertNull(href);
    }
```

**Comment by jhy** [comment]
Hi,

In the jsoup DOM, attributes are properties of an Element, but do not extend Node. (See the [Node tree](https://jsoup.org/apidocs/org/jsoup/nodes/package-tree.html) for details.) So they will not be directly returned by the [selectXpath](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#selectXpath(java.lang.String,java.lang.Class)).

Instead, just select the Element and then use the `attr` method on it to retrieve it.

Also, you might like to make your selector less specific so that if the site layout changes your extraction is less likely to be impacted. So you might do:

```java
Connection session = Jsoup.newSession();
Document doc = session.newRequest("https://commons.m.wikimedia.org/wiki/Main_Page").get();
String href = doc.selectXpath("//a[@title='Category:Images']").attr("abs:href");
System.out.println(href);
```

Which gives:

```text
https://commons.m.wikimedia.org/wiki/Category:Images
```
