### ISSUE TITLE
Support java.io.Reader

### ISSUE THREAD

**Issue by johannburkard** [jhy/jsoup#463]
JSoup supports Strings and InputStreams. That's great but supporting java.io.Reader would be nice. I assume some people assemble HTML in a StringBuilder or StringBuffer and the extra conversion step to a String doubles the amount of RAM required. With support for java.io.Reader, you could use StrBuilder (commons-lang) which has a convenient zero-copy [asReader() method](https://commons.apache.org/proper/commons-lang/javadocs/api-3.3.2/org/apache/commons/lang3/text/StrBuilder.html#asReader%28%29).

**Comment by yegortimoshenko** [comment]
@jhy HTML is [character-based format, not byte-based format](https://w3c.github.io/html/) which is the main reason why Reader should be supported. Jsoup includes functionality orthogonal to parsing/emitting HTML (i.e. `org.jsoup.Jsoup/connect`) which probably biased Jsoup to use InputStream instead of Reader.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by yegortimoshenko** [comment]
@jhy This definitely is still an issue. HTML format is defined in terms of characters, not bytes, which is why the way Jsoup currently handles this is incorrect, there is no way to parse a character stream agnostically.

**Comment by jhy** [comment]
Not sure I follow on the agnostic part? But I think it's covered now.

Since 1.11.1 I reimplemented the ChararacterReader and HTTP Connection Stream etc to use Readers. They're not buffered completely before the parse starts.

If you have a Reader, you can parse it with this method: [Parser#parseInput​(Reader inputHtml, String baseUri)](https://jsoup.org/apidocs/org/jsoup/parser/Parser.html#parseInput-java.io.Reader-java.lang.String-)

**Comment by yegortimoshenko** [comment]
@jhy Oh, great. Thanks!
