### ISSUE TITLE
Element.text() doesn't normalize '&nbsp;' whitespace

### ISSUE THREAD

**Issue by ChornHulio** [jhy/jsoup#529]
If you parse HTML encoded whitespaces, they won't be normalized in the Element.text() method. Furthermore you cannot replace them afterwards. 

> Document doc = Jsoup.parse( "\<html>\<body>This is  a\&nbsp; great\&nbsp;\&nbsp;test\</body>\</html>" );
> String str = doc.text();
> System.out.println( str );
> System.out.println( str.replaceAll( "\\s+", " " ));

Result:
> This is a  great  test
> This is a  great  test

(I'm using the current version of Jsoup, v. 1.8.1)

**Comment by tipabu** [comment]
The first result is because non-breaking spaces aren't considered collapsible whitespace ([nor should they be](http://www.w3.org/TR/REC-html40/struct/text.html#h-9.1)).

The second result is because regular expressions have a very limited set of characters that are considered whitespace; just [`[ \t\n\x0B\f\r]`](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#predef). If you want to match Unicode whitespace, it looks like you want [`[\p{Z}\s]+`](http://stackoverflow.com/questions/1822772/java-regular-expression-to-match-all-whitespace-characters).

**Comment by todd-cook** [comment]
Not a bug, the non-break space is being correctly encoded as NO-BREAK SPACE (U+00A0), e.g.

scala> var doc = org.jsoup.Jsoup.parse( "<html><body>This is a&nbsp; great&nbsp;&nbsp;test</body></html>" )
doc: org.jsoup.nodes.Document =
<html>
 <head></head>
 <body>
  This is a&nbsp; great&nbsp;&nbsp;test
 </body>
</html>

scala> doc.text().replaceAll("\\s+", " ")
res58: String = This is a  great  test


scala> (0 to doc.text().toList.size - 1).foreach( x => println(doc.text().charAt(x)  + " " +    Character.codePointAt( doc.text(), x)))
T 84
h 104
i 105
s 115
  32
i 105
s 115
  32
a 97
  160
  32
g 103
r 114
e 101
a 97
t 116
  160
  160
t 116
e 101
s 115
t 116

// 160 in UTF-16 is:  	NO-BREAK SPACE (U+00A0)
// e.g.:
scala>  println("space\u00A0break")
space break

your code would work if:

scala> doc.text().replaceAll("\u00A0+", " ").replaceAll("\\s+", " ")
res62: String = This is a great test

-- the other provided regex doesn't quite work

**Comment by dn-mib** [comment]
Hi, 
was this behaviour changed in the just released version? (https://jsoup.org/news/release-1.11.1)
probably in this commit https://github.com/jhy/jsoup/commit/d3f02400eca1c5cbf84212c46cebcff511536655

If this was previously not considered a bug, then why was it changed? We are using jsoup and relies on non-breaking-spaces to be preserved when extracting text-content from html.

Thanks for a really great html-library.

**Comment by dn-mib** [comment]
https://jsoup.org/news/release-1.11.2 now has `.wholeText()` on `Element`, so we will use that instead. Thanks.
