### ISSUE TITLE
Throws 500 exception with ignoreHttpErrors set to true

### ISSUE THREAD

**Issue by Vanaja1505** [jhy/jsoup#538]
Even if I set ignoreHttpErrors(true), my code throws IOException as 500 - Internal Server Error.

If I check with java.net.HttpURLConnection.getHeaderFields(), then the response is,
{}

The URL which I have this problem is
http://homemdllc.net

Can I get the status code even if HTTP error occurs in JSoup?

**Comment by AlkisKalogeris** [comment]
This is not a bug. It was answered here http://stackoverflow.com/questions/29003447/jsoup-throws-500-exception-with-ignorehttperrors-set-to-true#comment46301660_29003447 .

**Comment by Vanaja1505** [comment]
For the given url no HTTPException thrown as in reference link

**Comment by jhy** [comment]
@AlkisKalogeris that comment's been deleted, and I don't know what was there.

It seems like a bug to me; docs says it doesn't return an exception, and it does.

In this case, the bug is stemming from the server returning a Status 500 with Content-Length=0 (which is valid). When jsoup tries to read the error or input stream, Java throws an IO Exception, because there's no content.

I have fixed the bug by checking that content-length != 0 before trying to read the content.
@Vanaja1505 thanks for the report.

**Comment by Vanaja1505** [comment]
@jhy Thanks for your support...
