### ISSUE TITLE
from Version 1.7.3 to 1.8.2 umlaute in extended EscapeMode are not replaced

### ISSUE THREAD

**Issue by hlapidez** [jhy/jsoup#596]
doc = Jsoup.parse("<b>Überschrift</b>");
doc.outputSettings().escapeMode(EscapeMode.extended);
System.out.println(doc.toString());

1.7.3
`<b>&Uuml;berschrift</b>`

1.8.2
`<b>Überschrift</b>`

**Comment by jhy** [comment]
Hi,

The old behavior used to be: if a character had an entity in the selected EscapeMode list, replace it with the named escape code, regardless of whether it actually needs an escape. If it is not in the list, then check the character-set, and if it needs to be escaped, use a numerical escape.

The new behavior in 1.8.2 is: if a character needs escaping because it cannot be encoded using the currently selected character set, check if it is in the selected EscapeMode list. If it is, use that named escape, otherwise, use a numerical escape.

That is to say: you don't need to escape that character because the charset you're using supports it natively. Escaping it just makes for more network traffic / decoding overheard.

If for whatever reason you really do want to escape it (because downstream users don't actually support the charset you're using, for example), you should change charset. I.e. use "ascii" and you'll get effectively the same old behavior.
