### ISSUE TITLE
how to read chunked data

### ISSUE THREAD

**Issue by dongfangshangren** [jhy/jsoup#607]
I use Jsoup to do HTTP POST but I dont get back the chuncked response data. I read the source code,in org.jsoup.helper.HttpConnection.Response.execute(Connection.Request req, Response previousResponse) method, when conn.getContentLength() == 0 it return emptyByteBuffer. It can't work in chunked mode ,any other way can read the whole response data.

**Comment by jhy** [comment]
Chunked responses return a -1, so the == 0 should not be the issue here. I get/post to chunked encoding sites all the time without issue, so I don't think there's a fundamental problem. Perhaps something specific to the site you're hitting, or the URL implementation in your JRE.

Can you give me a code snippet and a site that demonstrates this issue you're having so it can be replicated?

**Comment by dongfangshangren** [comment]
Yes, there is an error in the server response,thank.
