### ISSUE TITLE
Attribute selector with a regular expression ([attr~=[^xyz]]) not working as expected

### ISSUE THREAD

**Issue by ks280first** [jhy/jsoup#638]
The method org.jsoup.select.Evaluator.AttributeWithValueMatching.matches() actually uses the Matcher method find() instead of matches().  

This causes many regular expressions not to function as expected like the negation expression in the title.

**Comment by ks280first** [comment]
Just to give a more concrete example, say we have the html:

<div attr="abc"></div>
<div attr="abe"></div>

and use select([attr~=[^c]+]), we still get both elements because the regex matcher is performing a find()

**Comment by jhy** [comment]
I think it's better to keep the current implementation. You can still run your regex on negations like this: `[attr~=^[^c]+$]` (i.e., expand the regex to match the full string).

Otherwise, you're going to force everyone who has a regex like `[attr~=a|b]` to change it to `[attr~=.*a|b.*]`. It makes the common case harder, and it'll break backward compatibility.
