### ISSUE TITLE
Support xpath 2.0 or greater

### ISSUE THREAD

**Issue by PatrickHuetter** [jhy/jsoup#653]
It would be fine if jsoup could support xpath queries inherently. There is a xpath extension called "xsoup" but this extension doesn't cover the whole xpath specification. https://github.com/code4craft/xsoup

I already tried using saxon in combination with jsoup (converting jsoup document to w3c document) to get full xpath support. This works but using the w3c document object model you get further problems while getting the original inner html for a node as you can see in my question on sf http://stackoverflow.com/questions/33635398/how-to-get-html-from-a-org-w3c-dom-node-in-java

I think if jsoup would support xpath many companies and developers would only use jsoup for data extraction and xpath purposes, due to the fact that jsoup offers one of the best parsing-engines for parsing malformed html documents (like many websites or html documents are).

**Comment by ceverlante** [comment]
+1

**Comment by speed** [comment]
+1

**Comment by hirocc** [comment]
＋1

**Comment by StephenOTT** [comment]
+1

**Comment by lll-01** [comment]
+1

**Comment by Jawn78** [comment]
+1

**Comment by tsigalko18** [comment]
+1

**Comment by jhy** [comment]
Now, if only I could trade your +1s in for an hour or so of open time each, that would be great! :) (Just hit the thumbs up if you're keen on this feature, no need for a +1 comment as it just adds clutter.)

So a question on the use case. Do you want xpath because there is functionality in the query mechanism that isn't in jsoup / css? What is missing that is impactful? Or is it more that you're more efficient in xpath because it's more familiar to you?

For the interface -- should it return Nodes instead of Elements, and allow attributes to be present as Nodes? Or return a w3c DOM?

**Comment by haruntuncay** [comment]
Hello @jhy , can I give this a go ?

**Comment by jhy** [comment]
Well it's been a little while coming (!) but I've just implemented native XPath support for jsoup. It's sitting in a PR now: #1629.

Please take a look! I'd love to get your feedback so that I can improve any gaps before landing this in the next release.

Thanks for your feedback and support on this feature (and your patience!)

**Comment by jhy** [comment]
I've merged this in now -- but would certainly welcome tests and feedback. Feedback can go onto the PR (#1629). Please raise new issues for any bugs or problems.
