### ISSUE TITLE
Keep XML entities in output

### ISSUE THREAD

**Issue by DavidePastore** [jhy/jsoup#660]
I want to see if I can get back the original string with Jsoup after a transform.

    Document doc = Jsoup.parse("<html><body><span>&rarr;</span></body></html>");
    String str = doc.toString();
    System.out.println(str);

Ouput here is:

    <html>
      <head></head>
      <body>
        <span>→</span>
      </body>
    </html>

What I want to obtain is:

    <html>
      <head></head>
      <body>
        <span>&rarr;</span>
      </body>
    </html>

Is it possible?

This is a [question on SO](http://stackoverflow.com/questions/33974674/on-jsoup-identity-transform#comment55721137_33974674).

Thanks

**Comment by petehouston** [comment]
@DavidePastore  yes,

```
doc.outputSettings().charset("ascii").escapeMode(Entities.EscapeMode.extended);
```

**Comment by DavidePastore** [comment]
Hi @petehouston, thanks for you solution but it outputs:

    <html>
      <head></head>
      <body>
        <span>&srarr;</span>
      </body>
    </html>

It has an additional `s` before `rarr`.

**Comment by petehouston** [comment]
@DavidePastore according to the HTML5 named character references, http://www.w3.org/TR/2011/WD-html5-20110113/named-character-references.html

`&srarr;` is the same as `&rarr;` also, same as `&RightArrow;`, `&ShortRightArrow;` ...

as you know, jsoup do validation (escape/unescape) while processing input and mapping the HTML entities defined in `entities-*.properties`; well, the since there are several entities' names represent in same Unicode value **\u02192** in your case, the mapping is done with the first match if I'm not mistaken.

**Comment by DavidePastore** [comment]
Thanks for your explanation @petehouston , you're the man!

**Comment by petehouston** [comment]
@DavidePastore you're welcome
