### ISSUE TITLE
next release date?

### ISSUE THREAD

**Issue by luksch** [jhy/jsoup#669]
I don't mean to be pushy, but over 5 months have passed since the last release and now and there is in my eyes at least one critical bug (https://github.com/jhy/jsoup/issues/614, https://github.com/jhy/jsoup/issues/664) apparent in the current release that seems to be fixed in the development branch? Is there are reason for the delay of a version that includes the fix? Any information on the current development state would be very much appreciated.

Thanks and keep up the wonderful work!

**Comment by ruippeixotog** [comment]
I'm also interested in knowing when will a new release happen. I also have [this issue](https://github.com/jhy/jsoup/issues/614) in one of my libraries that is suffering from the bug mentioned above. Can you release a 1.8.4 revision in order to take care of this, or is there some kind of schedule for jsoup releases? Thank you in advance!

**Comment by itaylor** [comment]
I'm also very interested getting an official release with #614 fixed.

**Comment by jhy** [comment]
Shooting for in the next two weeks.

**Comment by luksch** [comment]
that is really good news. I am looking forward to this release.

**Comment by jhy** [comment]
2016-Apr-16
