### ISSUE TITLE
parse() seems to drop leading <script> Element

### ISSUE THREAD

**Issue by TobiasHartlehnert** [jhy/jsoup#726]
I have HTML that may contain an embed code from Surveymonkey that I wish to run through jSoup to make sure that the resulting HTML is valid. XSS is not an issue here. Here's a sample HTML snippet:
```
<script type="text/javascript">console.log('foo');</script>
<div id="somecontent">some content</div>
<script type="text/javascript">console.log('bar');</script>
```
A `parse(htmlSnippet).body().html()` results in a string that's missing the first script-block altogether:
```
<div id="somecontent"> some content </div>
<script type="text/javascript">console.log('bar');</script>
```

The second script-block is not stripped, however.

If I prefix the whole thing with an empty `<span></span>`, jSoup keeps the script. So for the following snippet
```
<span></span><script type="text/javascript">console.log('foo');</script>
<div id="somecontent">some content</div>
<script type="text/javascript">console.log('bar');</script>
```

`parse(htmlSnippet).body().html()` returns
```
<span></span>
<script type="text/javascript">console.log('foo');</script>
<div id="somecontent"> some content </div>
<script type="text/javascript">console.log('bar');</script>
```

I think this qualifies as a bug.

**Comment by jhy** [comment]
If you are parsing a body fragment, you should use the `Jsoup.parseBodyFragment()` method. That forces all the content provided into the body, instead of trying to create a full valid document.

What's happening here is that you're asking Jsoup to parse a document. Per the spec, a HTML document has a head and a body, and when parsing, the first script goes into the head (because the body hadn't started yet, and the script is OK in the head. Then the parser sees a div, which can't go into the head, so it moves to the body. Once in body mode, every tag is kept in the body.

So your in your `span`, the script goes into the body because the parser had already switched to the body.

Chrome and other HTML parsers do the same thing:

<img width="449" alt="screen shot 2016-08-05 at 5 08 18 pm" src="https://cloud.githubusercontent.com/assets/76934/17453357/c4de5468-5b2f-11e6-969b-2a4f7d6485da.png">
