### ISSUE TITLE
Infinite self redirect

### ISSUE THREAD

**Issue by Ph3n1x** [jhy/jsoup#737]
There are strange constellations on the web. I have a problem with flowlz.com which sends

```
HTTP/1.1 302 Found
Date: Tue, 26 Jul 2016 21:05:34 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: close
Server: Apache
X-Powered-By: PHP/7.0.4
Cache-Control: no-cache, must-revalidate
Expires: Sat, 26 Jul 1997 05:00:00 GMT
Location:
```

This leads to infinite loop of redirect to itself. Maybe jsoup should check if the redirect url is the same as the current url and then stops the redirect?

**Comment by jhy** [comment]
Thanks, and sorry for the (very) late reply. I have not been able to replicate this, and have not seen other instances of similar reports. I do not believe there is an infinite redirect, as there has been a long-time check (since the initial redirect support was implemented, IIRC) for the number of chained redirects: https://github.com/jhy/jsoup/blob/607995d903570968ca0c41a82d7a37b89b979a4b/src/main/java/org/jsoup/helper/HttpConnection.java#L1085

I do not think it makes sense to stop following redirects if the URL has not changed. It's not likely, but the server may be setting cookies or changing other state that a subsequent fetch will succeed on.
