### ISSUE TITLE
Encoding issue with euro sign

### ISSUE THREAD

**Issue by Antoniossss** [jhy/jsoup#743]
Hello 
I have just run into a following problem.
http://www.planecheck.com/?ent=da&id=22105
On this page you can see plane price of € 44,900. However picking up text via Jsoup from proper node results in some "blank' characters - at least they are not showing in the sysout. 

How I load this document (this is only single, relevant frame):
`		this.document = Jsoup.parse(new URL(http://www.planecheck.com/aspdet.asp?nr=22105), 5000);`

How i want to get the data:
```
        this.mainElement = document.select("div > table > tbody> tr:eq(0)> td:eq(2)").first();
		Element element = mainElement.select("table:eq(9) table:eq(1) tr:eq(0) td:eq(1)").first();
		return this.price = nbsp(element.text());
```

This is totally reproductable with given lines of code. Euro sign is missing from the retrieved text.

**Comment by jhy** [comment]
Hi,

The problem here is that the site does not specify its output encoding type (in the header or in meta tags), leaving the UA to guess. Jsoup defaults to UTF-8, but the page is actually in Windows-1252.  Browsers implement an auto-detect mechanism for this case, but this is not implemented in Jsoup (because the way I think they work is to have a large character code frequency table to run hieuristics on, and I don't want to take on the file size bloat).

A workaround would be to get the response bytes (bodyAsBytes) method, then parse it through DataUtil(bytes, charset,...) and specificy the charset (`Windows-1252`).

BTW, a simpler selector for the price is: `td:has(:contains(Price)) ~ td b` - [demo](https://try.jsoup.org/~6pk_n8_cbViIyuA8iY4qLoxQwKo)

Let me know how you go.

**Comment by Antoniossss** [comment]
Feels like common sense to have additional method that accepts charset
parameter to hande such (but most probably rare) situation. Can we tag it
as feature request?

Thank you for your time. Manually parsing page gets euro sign just fine
just as you said.

6 sie 2016 18:52 "Jonathan Hedley" <notifications@github.com> napisał(a):

**Comment by Antoniossss** [comment]
thank you for addressing this issue!

14.08.2016 21:52 "Jonathan Hedley" <notifications@github.com> napisał(a):
