### ISSUE TITLE
Duplicate attributes added to nodes...

### ISSUE THREAD

**Issue by Stephan972** [jhy/jsoup#815]
Since Jsoup 1.10.1, some attributes aren't lowercased anymore.
Here is a sample code demonstrating the problem:
    
    @Test
    public void testSameAttributeWithDifferentCase() {
        String html = "<FORM><INPUT id=\"foo\" NAME=\"foo\" VALUE=\"\"></FORM>";

        Document doc = Jsoup.parse(html);
        Element foo = doc.select("#foo").first();
        foo.val("foo-value");

        // Failed assertion
        assertThat( foo.outerHtml(), is("<input id=\"foo\" NAME=\"foo\" VALUE=\"foo-value\">") );
        // foo.outerHtml() == <input id="foo" NAME="foo" VALUE="" value="foo-value">
    }

**Affected versions:** 1.10.1, 1.10.2

**Comment by complanboy2** [comment]
Hi Jhy,

I've been using this JSOUP and found impressive. How to contribute to this, I would like to fix issues and making it more useful ? Please point me to the contribution guidelines (I'm unable to find it on website ?), thank you.

**Comment by rfazi** [comment]
@complanboy2 
See this: https://help.github.com/articles/about-pull-requests/

**Comment by phoerious** [comment]
The problem is that the existing VALUE attribute is uppercase. I had the same issue while trying to change URLs in href attributes when the actual attribute name was HREF.

You can work around this issue by saving the value of the selected attribute, deleting it and then adding it again instead of simply trying to overwrite the existing attribute value.
