### ISSUE TITLE
My jsoup code can't work when I upgrade to 1.10.2 version

### ISSUE THREAD

**Issue by yuany** [jhy/jsoup#846]
There is link https://api.m.taopiaopiao.com/h5/mtop.film.mtopshowapi.getextendshowbyid/5.4/ I want to get the cookies from response using jsoup, It can work before I upgrade jsoup version from 1.10.1 to 1.10.2

After I read code between the versions  I found there is difference in the two versions:

in org.jsoup.helper.HttpConnection

> 1.10.2

private static String encodeUrl(String url) {
		if(url == null)
			return null;
    	return url.replaceAll(" ", "%20");
	}
> 1.10.1

private static URL encodeUrl(URL u) {
        try {
            //  odd way to encode urls, but it works!
            final URI uri = new URI(u.getProtocol(), u.getUserInfo(), u.getHost(), u.getPort(), u.getPath(), u.getQuery(), u.getRef());
            return new URL(uri.toASCIIString());
        } catch (Exception e) {
            return u;
        }
    }
I found the new `necodeUrl` method will get me a invalid result when the localtion is https://login.taobao.com/jump?target=https%3A%2F%2Fapi.m.taopiaopiao.com%2Fh5%2Fmtop.film.mtopshowapi.getextendshowbyid%2F5.4%2F%3Ftbpm%3D1 
the return result: https://login.taobao.com/jump?target=https%253A%252F%252Fapi.m.taopiaopiao.com%252Fh5%252Fmtop.film.mtopshowapi.getextendshowbyid%252F5.4%252F%253Ftbpm%253D1

**Comment by LukeButtersFunnelback** [comment]
The type has changed what exactly are you passing in? as it could not be:
```
encodeIUrl("http://...");
```
Is your problem that your URL is already encoded and so you end up double encoding it? if we simplify your URL to: `https://foo.com/space /https%25` and you asked for that URL to be encoded then you would probably expect the space to be replaced by `%20` if you expect that then you must also expect `%` needs to be encoded as well (because perhaps you are literally trying to send `https%25` in the path.

I think you need to not encode your URL at all and pass it to the encodeUrl method OR encode the URL completely yourself

**Comment by jhy** [comment]
This is fixed in 1.10.3 by 56a728d482ce0c88cd9513eca1e7c7585f0718f9

Will close this when released. Sorry about the issue!

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3
