### ISSUE TITLE
Open up outerHtmlHead / outerHtmlTail

### ISSUE THREAD

**Issue by jart** [jhy/jsoup#855]
We had to dip across package boundaries while writing https://github.com/bazelbuild/rules_closure/commit/6c5cbe3d51ccebe0f47ec207280533f2e80d1142 and it's something we'd like to rectify. Please advise us.

**Comment by cketti** [comment]
The methods are of little use outside of writing a custom serializer. In my opionion making `outerHtmlHead()` and `outerHtmlTail()` public would unnecessarily pollute the API of some of the most often used jsoup classes.

How about extracting the `outerHtml*` code to separate classes, e.g. `ElementPrinter`, `TextNodePrinter` etc.? In your custom HTML printer you'd have to add some runtime type checks to figure out which printer class to use. But I can't imagine this having a huge performance impact.
Of course this is only useful to you if jsoup adopts the approach. Violating the package boundary is less maintenance-intensive than keeping a copy of the serialization code in sync with upstream.

**Comment by jart** [comment]
APIs should ideally make all use cases possible, even accomplishing it is not elegant. I'm more concerned about performance and time complexity.

I'd rather we keep doing what we're doing than ask you guys to implement a bunch of new classes that would require a lot of reflection. Those classes would probably pollute the API a lot more than making these methods public, or upstreaming #854.

**Comment by cketti** [comment]
Users of the library probably won't notice a couple more classes being available in the class path. However, because of the auto-completion basically every IDE offers, they will notice new and somewhat strange methods on the classes they do use all the time.

But I'm just a person with an opinion, not someone who has the power to make the call for jsoup. So please don't abandon your attempt to get this changed just because I don't like it.

As for the "require a lot of reflection" part: you'd only need `instanceof` or `getClass()`. Both things that are reasonably fast. Also, your `Html5Printer` code already contains a bunch of `instanceof` operations.

**Comment by jart** [comment]
It can be named zIgnoreMeOuterHtmlHead. I'm not concerned. The problem is that we need to put the code we're writing into an different codebase in order to our jobs.

`instanceof` and `getClass` are still reflection. In the case of `Html5Printer` the only alternatives the JSoup API provided were `String` comparisons. It would be better if those strings were interned or an enum field was provided, since reflection usually indicates OOP design could be improved.

**Comment by jhy** [comment]
Thanks for the idea, and sorry for the late reply. I don't currently plan on changing this as I haven't seen much demand. Per @cketti's point, if anything, I would prefer to add serializing classes. But you mention you don't want that.
