### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Mdhaker** [jhy/jsoup#870]
Hello, is there anyway to handle Pagination via Jsoup ?

**Comment by jjpatel361** [comment]
If the pages are non persistent then you can find URL patterns and then use JSOUP for each link
Most sites implement standard URL formatting like

`http://www.abc.com/product/1`
`http://www.abc.com/product/2`
`http://www.abc.com/product/3`

or with query parameter
`http://www.abc.com/product/page=3&`

some of them might be using persistent data i.e you have to visit the first page and then to access any other page you have to send some cookies and headers received from first page visit.

**Comment by Mdhaker** [comment]
I already did that, and I'm asking about ajax based pagination

**Comment by jjpatel361** [comment]
Well, I can't think of a way to do it in a purely JSOUP way. Primarily, because the AJAX calling is a part of JS code execution and JSOUP isn't a tool to execute these scripts or evaluate them at runtime. I prefer doing the Selenium based, in such cases.  
Although, if AJAX is handled some other way I would love to see that solution.
