### ISSUE TITLE
jsoup 1.9.2 and later are available on MavenCentral, but not JCenter

### ISSUE THREAD

**Issue by Thunderforge** [jhy/jsoup#888]
jsoup 1.9.2 and higher (including 1.10.x) are [available on MavenCentral](http://central.maven.org/maven2/org/jsoup/jsoup/). However, they are not [available on JCenter](https://bintray.com/jhy/maven/org.jsoup%3Ajsoup), where the latest version is 1.9.1. 

The comments on issue #692 suggest that JCenter is supposed to proxy Maven Central, however this is not happening with these later jsoup versions.

**Comment by bluetata** [comment]
you can used by below URL that is all version about jsoup
[http://mvnrepository.com/artifact/org.jsoup/jsoup](http://mvnrepository.com/artifact/org.jsoup/jsoup)

**Comment by kno10** [comment]
You need to report this to jcenter/bintray. They are doing the sync.

**Comment by jhy** [comment]
So I've been trying to work with Bintray to get this fixed. Apparently if you "take ownership" (associate an account) for a package, it silently stops syncing from Maven Central. They want to make you use Bintray to push into Maven Central, or otherwise do every release by hand. Seems a cynical approach to get usage up. And their tool won't let me delete the package now.

So until their CS can help out, I'd suggest just not trying to fetch releases from Bintray / JCenter / Jfrog / whatever it's called. Just use Maven Central.

**Comment by jhy** [comment]
Per their instructions I deleted my Maven repo in Bintray (which was created when I took "ownership" of jsoup there.

And it's now got a proxy version that's tracking again correctly: https://bintray.com/bintray/jcenter/org.jsoup:jsoup
