### ISSUE TITLE
TrustAllX509TrustManager issue

### ISSUE THREAD

**Issue by mherrav** [jhy/jsoup#909]
Hi!

First of all, thank you for your hard work!

Got an issue to report regarding the `initUnSecureTSL()` method in the `HttpConnection` class.

Building an Android project that contains Jsoup fails with the following Lint error:

```
org/jsoup/helper/HttpConnection$Response$2.class: checkServerTrusted is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers

This check looks for X509TrustManager implementations whose checkServerTrusted or checkClientTrusted methods do nothing (thus trusting any certificate chain) which could result in insecure network traffic caused by trusting arbitrary TLS/SSL certificates presented by peers.
```

Furthermore, I've encountered several articles where this kind of error causes apps submitted to GooglePlay to be rejected, i.e: http://techqa.info/programming/question/37621202/Android-X509TrustManager-app-rejected-google-play

One could, of course, suppress the warning. But this won't be a real solution to the problem.

Removing the calls to the problematic method in the codebase does not seem to have any effect on the functionality of the library. 

Is there any need for this logic to be in the library at all? I would like to learn more about the reason for this.

I'd be grateful if you could help me with this problem. Thanks!

**Comment by jhy** [comment]
Hi, thanks for the feedback.

It's so you can disable TLS certificate checks. See [docs](https://jsoup.org/apidocs/org/jsoup/Connection.html#validateTLSCertificates-boolean-) and [code](https://github.com/jhy/jsoup/blob/040ce712b73fcb3ff16b7d8dda1246ccd23a6988/src/main/java/org/jsoup/Connection.java#L146-L146).

They are only disabled if you (as the developer) use that option; the checks are enabled by default.

I haven't received any feedback or indicators that Google Play is rejecting apps because of using jsoup / because of this option. [AppBrain reports](https://www.appbrain.com/stats/libraries/details/jsoup/jsoup%3A-java-html-parser) many active installs.

If you're worried about it, you could always Proguard it out.

**Comment by mherrav** [comment]
Got it!

Thank you for your prompt response. I'll look into the solutions you suggested.

All the best.

**Comment by tanelmae** [comment]
Hi!
Google Play scans change over time and that AppBrain report is not really relevant. Google Play has started scanning app code for disabling certificate checks and will reject it whether that code is reachable or not. All apps should use Proguard for for release build but not all do. Not to mention that it depends on details of the implementation whether Produard will detect the code as unused.

All in all, it would be much more developer friendly for the library code not to include such hacks. Unless this is fixed in jsoup we will soon see fork for Android and I don't think that would be the most optimal outcome for everyone.
Please also do note that you have received feedback about this problem.

**Comment by jhy** [comment]
Can track in #912
