### ISSUE TITLE
TLS Certificate Bypassable, throws warnings

### ISSUE THREAD

**Issue by TannerS** [jhy/jsoup#912]
Had to use this in a app at work but the security report brought back the following. I wanted to know if anyone had any insight on this and if this is fixed.

See pic below

<img width="869" alt="screen shot 2017-07-07 at 9 57 57 am" src="https://user-images.githubusercontent.com/8866319/27968243-14dd78f8-62fb-11e7-9789-4aaecea07d78.png">

**Comment by jhy** [comment]
This is because there's an option (not enabled by default) to disable TLS cert ([request. validateTLSCertificates(boolean)](https://jsoup.org/apidocs/org/jsoup/Connection.html#validateTLSCertificates-boolean-)). If you haven't set that option, the custom trust manager is not used and regular validation still occurs.

There's a bit of a tradeoff here - lots of hosts run certs that fail validation but that people still want to make requests to, so the option is available to disable them.

However I'm starting to see feedback like this where analysis tools, and potentially Google Play, are looking for this and warning / failing on it.

I think the path may be to remove the implementation from the core code and have a plugin mechanism that developers can provide their own impl (and make sure the core code doesn't trip these analysis).

PRs welcome on this.

**Comment by jhy** [comment]
For a bit of background, see PR #343 (implemented) and PR #808 (not implemented)

**Comment by TannerS** [comment]
Thanks for the reply. One thing to note is this report shows this problem is not a warning by a failure to their security protocols. However, i will see what I can do with the info provided. thank you sir.

**Comment by jhy** [comment]
Missed closing this - deprecated and removed - bf6667c439a1fa29ea50d531b65633ffe150d16b
