### ISSUE TITLE
Jsoup parse incorrectly self closed tags inside <noscript> tag in the <head>

### ISSUE THREAD

**Issue by husam-otri** [jhy/jsoup#927]
Jsoup parse incorrectly  self closed tags - iframe, img - inside <noscript> tag in the head

for example:
```<html>
<head>
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-W3LK7G" height="0" width="0" style="display:none;visibility:hidden"/> </noscript>
<noscript><img src="http://example.com" /></noscript>
<meta />
</head>
<body>
<div>main</div>
</body>
</html>


the parsing result is:
<html>
 <head> 
  <noscript>
   &lt;iframe src="//www.googletagmanager.com/ns.html?id=GTM-W3LK7G" height="0" width="0" style="display:none;visibility:hidden"&gt; 
  </noscript> 
  <noscript>
   &lt;img src="http://example.com"&gt;
  </noscript> 
  <meta> 
 </head> 
 <body> 
  <div>
   main
  </div>  
 </body>
</html>

**Comment by robsonpeixoto** [comment]
@husam-otri it looks an intentional behave.
https://github.com/jhy/jsoup/blob/master/src/test/java/org/jsoup/parser/HtmlParserTest.java#L512-L516
https://github.com/jhy/jsoup/commit/ee5d4dffb382e362b52af67a53dffc92cc9ced49

mdn reference: https://developer.mozilla.org/en/docs/Web/HTML/Element/noscript

**Comment by jhy** [comment]
The spec has noscript just containing text content when scripting is disabled (which it is because jsoup doesn't support scripting). I could imagine disabling that check though and treating it as a regular tag.

**Comment by blacelle** [comment]
A related issue is that `.text()` on 
```
<head>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=387891508999354&ev=PageView&noscript=1"/>
</noscript>
</head>
```

returns `<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=387891508999354&ev=PageView&noscript=1"/>` while I would expect an empty String.

**Comment by jhy** [comment]
Closing - the current behavior is to follow the [HTML spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inheadnoscript:~:text=parsing%20algorithm.-,A%20start%20tag%20whose%20tag%20name%20is%20%22noscript%22%2C%20if%20the%20scripting%20flag%20is%20enabled,-A%20start%20tag) as if we are in scripting mode. Which parses `noscript` element contents as raw text. This is designed to align to how browsers parse by default, particularly so that validation (e.g. via the Cleaner) aligns to actual browsers.
