### ISSUE TITLE
Pretty print invalidates CDATA-script-tag-js in XML-Mode 

### ISSUE THREAD

**Issue by fkretzer** [jhy/jsoup#965]
Any ideas why this does not work: http://try.jsoup.org/~ZHbgr1Dq8s0aVjx-piYV9PfHf3E ?
Script seems to be syntactically correct.
Thanks in advance for any hints!

**Comment by jhy** [comment]
What's happening is that:
-because it's set to XML mode, nothing knows that `script` tags should be space-preserved
- currently in jsoup, cdata tags are treated only as an escaping mechanism, they are not round-trippped
- so with pretty-printing on, the script is normalized on one line, and the whole script is commented out because of the comment before the cdata

I'd say the immediate solution is to leave of pretty printing if you need to parse in XML mode. Longer term solution would probably be for jsoup (optionally?) preserve cdata wrappers as a different node type than a TextNode (maybe an extended comment type?)

**Comment by fkretzer** [comment]
Many thanks for the fast and detailed explanation! Disabling pretty print is an acceptable workaround in my case. In my opinion CDATA-segments should not be touched with and without pretty print, but i don't know if this would break existing use-cases for some people.

**Comment by jhy** [comment]
Let's keep it open for now, to track a better fix

**Comment by jhy** [comment]
Thanks, this is implemented now.

**Comment by fkretzer** [comment]
You are welcome! Thanks for your library.
