### ISSUE TITLE
Feature Request - Pass encoding in methods that return a Document

### ISSUE THREAD

**Issue by julianomqs** [jhy/jsoup#989]
Hi,

I'm using your library in some projects here, it's great.

But I miss something to set the encoding when executing a request to a document, like

```java
Jsoup.connect(URL)
	.timeout(timeout)
	.data("abcd", "1234")
	.userAgent(USER_AGENT)
	.post()
```

It would be great something like this:

```java
Jsoup.connect(URL)
	.timeout(timeout)
	.data("abcd", "1234")
	.userAgent(USER_AGENT)
	.post("ISO-8859-1")
```

What do you think?

**Comment by krystiangorecki** [comment]
I have a different idea for possible implementation. 
Encoding should be set in `Content-Type` request header like this:
`.header("Content-Type", "application/x-www-form-urlencoded ; charset=UTF-8");`
Then in
`org.jsoup.helper.HttpConnection.Response.serialiseRequestUrl(Request)`
instead of using default value:
```           
url.append(URLEncoder.encode(keyVal.key(), DataUtil.defaultCharset))
   .append('=')
   .append(URLEncoder.encode(keyVal.value(), DataUtil.defaultCharset));
```
we should use value passed in header.

**Comment by krystiangorecki** [comment]
@julianomqs I just discovered this should already be possible using `.postDataCharset("ISO-8859-1")`. Have you tried this?

**Comment by julianomqs** [comment]
@krystiangorecki  I'm really sorry, I messed up in the issue description.

I created a new issue with the correct description, to not make this one more confusing.

Here it is: #997
